import type { Message } from './messageTypes'
import type { ContentPart } from '../../domains/workbench/content/contentPartSchema.ts'

type VisualQaMessage = Message & { semanticParts?: readonly ContentPart[] }

const LONG_TOOL_OUTPUT = Array.from({ length: 36 }, (_, index) =>
  `src/components/chat/ChatView.tsx:${index + 1}: matched display path`,
).join('\n')

const ANSI_BASH_OUTPUT = '\u001b[32mPASS\u001b[0m  npm run build\n\u001b[33mWARN\u001b[0m  bundle exceeds 500 kB\n\u001b[31mERR\u001b[0m   0 errors'

const TEST_OUTPUT = [
  'test-chat-info-layer.mts      PASS',
  'test-message-persistence.mts  PASS',
  'test-tool-status.mts          PASS',
  'test-spinner-frames.mts       PASS',
  'test-thought-block-visual.mts PASS',
  '5 suites passed · 0 failed',
].join('\n')

/** 浏览器预览使用的完整消息样本，覆盖当前 renderer 的主要分支。 */
export const MOCK_MESSAGES: VisualQaMessage[] = [
  {
    id: 'mock-user-markdown',
    role: 'user',
    sender: 'local:demo',
    content: '请检查 `ChatView.tsx`，并用 Markdown 汇报结果。重点观察 thought、tool 链和生成状态。',
    time: '10:24',
  },
  {
    id: 'mock-thinking',
    role: 'reasoning',
    sender: 'peri',
    content: '先读取源码，再区分 renderer、tool 状态和持久化边界。\n确认消息流如何进入 streamingThinking，再检查终态如何写回历史消息。',
    time: '10:24',
    thoughtStartedAt: Date.now() - 9200,
    thoughtDurationMs: 9200,
  },
  {
    id: 'mock-read',
    role: 'tool',
    sender: 'tool:Read',
    content: '',
    toolName: 'Read',
    toolKind: 'read',
    toolInput: 'src/components/chat/ChatView.tsx',
    toolOutput: 'function ChatView() {\n  return <MessageList />\n}\n\nexport default ChatView',
    toolOutputLines: 5,
    toolStatus: 'completed',
    time: '10:24',
  },
  {
    id: 'mock-grep',
    role: 'tool',
    sender: 'tool:Grep',
    content: '',
    toolName: 'Grep',
    toolKind: 'search',
    toolInput: 'MessageRenderBoundary',
    toolOutput: LONG_TOOL_OUTPUT,
    toolOutputLines: 36,
    toolStatus: 'completed',
    time: '10:24',
  },
  {
    id: 'mock-thinking-tool-chain',
    role: 'reasoning',
    sender: 'peri',
    content: '读取结果确认消息行经过边界组件。下一步验证连续 tool 的 connector 是否跟随前一个 tool 的终态着色。',
    time: '10:24',
    thoughtStartedAt: Date.now() - 6800,
    thoughtDurationMs: 6800,
  },
  {
    id: 'mock-bash',
    role: 'tool',
    sender: 'tool:Bash',
    content: '',
    toolName: 'Bash',
    toolKind: 'execute',
    toolInput: 'npm run build',
    toolOutput: ANSI_BASH_OUTPUT,
    toolOutputLines: 3,
    toolStatus: 'completed',
    time: '10:24',
  },
  {
    id: 'mock-edit',
    role: 'tool',
    sender: 'tool:Edit',
    content: '',
    toolName: 'Edit',
    toolKind: 'edit',
    toolInput: 'src/components/chat/ChatView.tsx',
    toolOutput: '- const messages = rawMessages\n+ const messages = prepareRenderableMessages(rawMessages)',
    toolOutputLines: 2,
    toolStatus: 'completed',
    contentBlocks: [
      {
        type: 'tool_diff_content',
        title: 'ChatView.tsx',
        oldText: 'const messages = rawMessages\n',
        newText: 'const messages = prepareRenderableMessages(rawMessages)\n',
      },
    ],
    time: '10:24',
  },
  {
    id: 'mock-write-failed',
    role: 'tool',
    sender: 'tool:Write',
    content: '',
    toolName: 'Write',
    toolKind: 'write',
    toolInput: 'src/generated/missing.ts',
    toolOutput: 'permission denied: workspace is read-only',
    toolOutputLines: 1,
    toolStatus: 'failed',
    time: '10:24',
  },
  {
    id: 'mock-recovery-thought',
    role: 'reasoning',
    sender: 'peri',
    content: 'Write 被拒绝，不能把这个失败误判成整个生成失败。保留错误 tool 行，继续展示后续验证结果。',
    time: '10:25',
    thoughtStartedAt: Date.now() - 4300,
    thoughtDurationMs: 4300,
  },
  {
    id: 'mock-task-running',
    role: 'tool',
    sender: 'tool:Task',
    content: '',
    toolName: 'Task',
    toolKind: 'plan',
    toolInput: '运行前端回归测试',
    toolStatus: 'in_progress',
    running: true,
    time: '10:25',
  },
  {
    id: 'mock-tool-waiting',
    role: 'tool',
    sender: 'tool:Fetch',
    content: '',
    toolName: 'Fetch',
    toolKind: 'fetch',
    toolInput: '等待远端响应',
    toolStatus: 'waiting',
    time: '10:25',
  },
  {
    id: 'mock-tool-queued',
    role: 'tool',
    sender: 'tool:UnknownQueue',
    content: '',
    toolName: 'UnknownQueue',
    toolKind: 'unknown',
    toolInput: '等待执行',
    toolStatus: 'queued',
    time: '10:25',
  },
  {
    id: 'mock-tool-cancelled',
    role: 'tool',
    sender: 'tool:Shell',
    content: '',
    toolName: 'Shell',
    toolKind: 'execute',
    toolInput: '长时间运行的命令',
    toolOutput: 'cancelled by user',
    toolOutputLines: 1,
    toolStatus: 'cancelled',
    time: '10:25',
  },
  {
    id: 'mock-tool-unknown',
    role: 'tool',
    sender: 'tool:FutureTool',
    content: '',
    toolName: 'FutureTool',
    toolInput: '未知工具 fallback',
    toolStatus: 'future-status',
    time: '10:25',
  },
  {
    id: 'mock-final-thinking',
    role: 'reasoning',
    sender: 'peri',
    content: '测试结果已经返回。最后整理状态摘要：成功、失败、等待和未知状态都必须保持可辨识，但不能让状态色压过正文。',
    time: '10:26',
    thoughtStartedAt: Date.now() - 12300,
    thoughtDurationMs: 12300,
  },
  {
    id: 'mock-test-output',
    role: 'tool',
    sender: 'tool:Bash',
    content: '',
    toolName: 'Bash',
    toolKind: 'execute',
    toolInput: 'npm run test:frontend -- --focused chat',
    toolOutput: TEST_OUTPUT,
    toolOutputLines: 6,
    toolStatus: 'completed',
    time: '10:26',
  },
  {
    id: 'mock-test-watch',
    role: 'tool',
    sender: 'tool:Watch',
    content: '',
    toolName: 'Watch',
    toolKind: 'watch',
    toolInput: '观察 frontend regression 输出',
    toolOutput: 'watching 5 suites\nno changes detected',
    toolOutputLines: 2,
    toolStatus: 'completed',
    time: '10:26',
  },
  {
    id: 'mock-assistant-markdown',
    role: 'assistant',
    sender: 'peri',
    content: '# 检查结果\n\n发现一个需要注意的渲染边界：`streamingText` 不应写回历史消息。\n\n> 建议先保持 raw message 和 render message 分离。\n\n- 已确认消息列表使用 memo row\n- 已确认 tool output 有 sanitizer\n- 已确认取消状态需要最终收敛\n- 已确认 thought 结束时记录真实耗时\n\n| 项目 | 状态 |\n| --- | --- |\n| build | PASS |\n| frontend tests | PASS |\n| thought visual | PASS |\n\n详情见 [渲染基线](https://example.com/rendering)。',
    time: '10:26',
  },
  {
    id: 'mock-assistant-code',
    role: 'assistant',
    sender: 'peri',
    content: '可以使用下面的类型约束：\n\n```ts\nexport type ToolState =\n  | \'running\'\n  | \'completed\'\n  | \'failed\'\n```',
    time: '10:26',
  },
  {
    id: 'mock-assistant-plain',
    role: 'assistant',
    sender: 'peri',
    content: '纯文本 fast path 仍然保留换行和原始文本节奏。\n第二行用于观察长消息之间的垂直节奏。',
    time: '10:26',
  },
  {
    id: 'mock-assistant-structured',
    role: 'assistant',
    sender: 'peri',
    content: '结构化内容富渲染验收',
    semanticParts: [
      { kind: 'location', path: '/workspace/src/renderers/solid-workbench/SolidWorkbenchApp.solid.tsx', line: 1056, column: 3 },
      { kind: 'progress', current: 3, total: 4, message: '索引 renderer kinds' },
      { kind: 'list', title: '富内容边界', items: [
        { kind: 'markdown', text: '**Markdown** 保持语义渲染' },
        { kind: 'code', text: 'const renderer = "solid"', language: 'ts' },
        { source_path: '/workspace/report.md', score: 0.98 },
      ] },
      { kind: 'key-value', entries: { provider: 'ACP', replaySafe: true, revision: 7 } },
      { kind: 'json', value: { nested: { expanded: false, streaming: true }, tags: ['typed', 'bounded'] } },
      { kind: 'tool-use', name: 'Fetch', status: 'running', input: { url: 'https://example.test/api', method: 'GET' }, requestId: 'request-42' },
      { kind: 'tool-result', name: 'Search', status: 'completed', latencyMs: 42, parts: [
        { kind: 'markdown', text: '找到 **2** 项结果' },
        { kind: 'location', path: '/workspace/src/app.ts', line: 7 },
      ] },
    ],
    time: '10:26',
  },
  {
    id: 'mock-empty-assistant',
    role: 'assistant',
    sender: 'peri',
    content: '',
    time: '10:26',
  },
  // ── W4 之后新增：plan/search 语义 kind 展示（ToolCard data-kind=plan/search）──
  {
    id: 'mock-plan-thought',
    role: 'reasoning',
    sender: 'peri',
    content: '整理剩余任务：①确认右栏搜索接线 ②跑快照搜索 ③汇总改动面。计划以 plan 工具输出，便于任务树展示。',
    time: '10:27',
    thoughtStartedAt: Date.now() - 2100,
    thoughtDurationMs: 2100,
  },
  {
    id: 'mock-tool-plan',
    role: 'tool',
    sender: 'tool:Plan',
    content: '',
    toolName: 'Plan',
    toolKind: 'plan',
    toolInput: '右栏搜索接线',
    toolOutput: '1. [in_progress] 右栏搜索接线\n2. [ ] 快照搜索回归\n3. [ ] 汇总改动面',
    toolOutputLines: 3,
    toolStatus: 'completed',
    time: '10:27',
  },
  {
    id: 'mock-tool-search',
    role: 'tool',
    sender: 'tool:Search',
    content: '',
    toolName: 'Search',
    toolKind: 'search',
    toolInput: 'snapshotSearch 命中样例',
    toolOutput: 'src/sheets/search/SearchSheetView.tsx:12: 跨会话快照搜索（W3-03）\nsrc/domains/search/snapshotSearch.ts:24: isMessageSnapshotKey 前缀 pylon-msgs-',
    toolOutputLines: 2,
    toolStatus: 'completed',
    time: '10:27',
  },
  {
    id: 'mock-plan-assistant',
    role: 'assistant',
    sender: 'peri',
    content: '计划小结：**右栏搜索接线**已完成并锁定行为，快照搜索与汇总改动面待用户确认后收尾。',
    time: '10:27',
  },
]

export function createMockMessages(): Message[] {
  return MOCK_MESSAGES.map(message => ({ ...message }))
}
