import type { Message } from './messageTypes'

const LONG_TOOL_OUTPUT = Array.from({ length: 36 }, (_, index) =>
  `src/components/chat/ChatView.tsx:${index + 1}: matched display path`,
).join('\n')

const ANSI_BASH_OUTPUT = '\u001b[32mPASS\u001b[0m  npm run build\n\u001b[33mWARN\u001b[0m  bundle exceeds 500 kB\n\u001b[31mERR\u001b[0m   0 errors'

const TEST_OUTPUT = [
  'test-chat-info-layer.mts      PASS',
  'test-message-persistence.mts  PASS',
  'test-tool-status.mts          PASS',
  'test-spinner-frames.mts       PASS',
  'test-thought-block-visual.mts PASS',
  '5 suites passed · 0 failed',
].join('\n')

/** 浏览器预览使用的完整消息样本，覆盖当前 renderer 的主要分支。 */
export const MOCK_MESSAGES: Message[] = [
  {
    id: 'mock-user-markdown',
    role: 'user',
    sender: 'local:demo',
    content: '请检查 `ChatView.tsx`，并用 Markdown 汇报结果。重点观察 thought、tool 链和生成状态。',
    time: '10:24',
  },
  {
    id: 'mock-thinking',
    role: 'reasoning',
    sender: 'peri',
    content: '先读取源码，再区分 renderer、tool 状态和持久化边界。\n确认消息流如何进入 streamingThinking，再检查终态如何写回历史消息。',
    time: '10:24',
    thoughtStartedAt: Date.now() - 9200,
    thoughtDurationMs: 9200,
  },
  {
    id: 'mock-read',
    role: 'tool',
    sender: 'tool:Read',
    content: '',
    toolName: 'Read',
    toolInput: 'src/components/chat/ChatView.tsx',
    toolOutput: 'function ChatView() {\n  return <MessageList />\n}\n\nexport default ChatView',
    toolOutputLines: 5,
    toolStatus: 'completed',
    time: '10:24',
  },
  {
    id: 'mock-grep',
    role: 'tool',
    sender: 'tool:Grep',
    content: '',
    toolName: 'Grep',
    toolInput: 'MessageRenderBoundary',
    toolOutput: LONG_TOOL_OUTPUT,
    toolOutputLines: 36,
    toolStatus: 'completed',
    time: '10:24',
  },
  {
    id: 'mock-thinking-tool-chain',
    role: 'reasoning',
    sender: 'peri',
    content: '读取结果确认消息行经过边界组件。下一步验证连续 tool 的 connector 是否跟随前一个 tool 的终态着色。',
    time: '10:24',
    thoughtStartedAt: Date.now() - 6800,
    thoughtDurationMs: 6800,
  },
  {
    id: 'mock-bash',
    role: 'tool',
    sender: 'tool:Bash',
    content: '',
    toolName: 'Bash',
    toolInput: 'npm run build',
    toolOutput: ANSI_BASH_OUTPUT,
    toolOutputLines: 3,
    toolStatus: 'completed',
    time: '10:24',
  },
  {
    id: 'mock-edit',
    role: 'tool',
    sender: 'tool:Edit',
    content: '',
    toolName: 'Edit',
    toolInput: 'src/components/chat/ChatView.tsx',
    toolOutput: '- const messages = rawMessages\n+ const messages = prepareRenderableMessages(rawMessages)',
    toolOutputLines: 2,
    toolStatus: 'completed',
    time: '10:24',
  },
  {
    id: 'mock-write-failed',
    role: 'tool',
    sender: 'tool:Write',
    content: '',
    toolName: 'Write',
    toolInput: 'src/generated/missing.ts',
    toolOutput: 'permission denied: workspace is read-only',
    toolOutputLines: 1,
    toolStatus: 'failed',
    time: '10:24',
  },
  {
    id: 'mock-recovery-thought',
    role: 'reasoning',
    sender: 'peri',
    content: 'Write 被拒绝，不能把这个失败误判成整个生成失败。保留错误 tool 行，继续展示后续验证结果。',
    time: '10:25',
    thoughtStartedAt: Date.now() - 4300,
    thoughtDurationMs: 4300,
  },
  {
    id: 'mock-task-running',
    role: 'tool',
    sender: 'tool:Task',
    content: '',
    toolName: 'Task',
    toolInput: '运行前端回归测试',
    toolStatus: 'in_progress',
    running: true,
    time: '10:25',
  },
  {
    id: 'mock-tool-waiting',
    role: 'tool',
    sender: 'tool:Fetch',
    content: '',
    toolName: 'Fetch',
    toolInput: '等待远端响应',
    toolStatus: 'waiting',
    time: '10:25',
  },
  {
    id: 'mock-tool-queued',
    role: 'tool',
    sender: 'tool:UnknownQueue',
    content: '',
    toolName: 'UnknownQueue',
    toolInput: '等待执行',
    toolStatus: 'queued',
    time: '10:25',
  },
  {
    id: 'mock-tool-cancelled',
    role: 'tool',
    sender: 'tool:Shell',
    content: '',
    toolName: 'Shell',
    toolInput: '长时间运行的命令',
    toolOutput: 'cancelled by user',
    toolOutputLines: 1,
    toolStatus: 'cancelled',
    time: '10:25',
  },
  {
    id: 'mock-tool-unknown',
    role: 'tool',
    sender: 'tool:FutureTool',
    content: '',
    toolName: 'FutureTool',
    toolInput: '未知工具 fallback',
    toolStatus: 'future-status',
    time: '10:25',
  },
  {
    id: 'mock-final-thinking',
    role: 'reasoning',
    sender: 'peri',
    content: '测试结果已经返回。最后整理状态摘要：成功、失败、等待和未知状态都必须保持可辨识，但不能让状态色压过正文。',
    time: '10:26',
    thoughtStartedAt: Date.now() - 12300,
    thoughtDurationMs: 12300,
  },
  {
    id: 'mock-test-output',
    role: 'tool',
    sender: 'tool:Bash',
    content: '',
    toolName: 'Bash',
    toolInput: 'npm run test:frontend -- --focused chat',
    toolOutput: TEST_OUTPUT,
    toolOutputLines: 6,
    toolStatus: 'completed',
    time: '10:26',
  },
  {
    id: 'mock-test-watch',
    role: 'tool',
    sender: 'tool:Watch',
    content: '',
    toolName: 'Watch',
    toolInput: '观察 frontend regression 输出',
    toolOutput: 'watching 5 suites\nno changes detected',
    toolOutputLines: 2,
    toolStatus: 'completed',
    time: '10:26',
  },
  {
    id: 'mock-assistant-markdown',
    role: 'assistant',
    sender: 'peri',
    content: '# 检查结果\n\n发现一个需要注意的渲染边界：`streamingText` 不应写回历史消息。\n\n> 建议先保持 raw message 和 render message 分离。\n\n- 已确认消息列表使用 memo row\n- 已确认 tool output 有 sanitizer\n- 已确认取消状态需要最终收敛\n- 已确认 thought 结束时记录真实耗时\n\n| 项目 | 状态 |\n| --- | --- |\n| build | PASS |\n| frontend tests | PASS |\n| thought visual | PASS |\n\n详情见 [渲染基线](https://example.com/rendering)。',
    time: '10:26',
  },
  {
    id: 'mock-assistant-code',
    role: 'assistant',
    sender: 'peri',
    content: '可以使用下面的类型约束：\n\n```ts\nexport type ToolState =\n  | \'running\'\n  | \'completed\'\n  | \'failed\'\n```',
    time: '10:26',
  },
  {
    id: 'mock-assistant-plain',
    role: 'assistant',
    sender: 'peri',
    content: '纯文本 fast path 仍然保留换行和原始文本节奏。\n第二行用于观察长消息之间的垂直节奏。',
    time: '10:26',
  },
  {
    id: 'mock-empty-assistant',
    role: 'assistant',
    sender: 'peri',
    content: '',
    time: '10:26',
  },
]

export function createMockMessages(): Message[] {
  return MOCK_MESSAGES.map(message => ({ ...message }))
}
