/**
 * 区域层 · 出厂区域预设数据 —— terminal 桶 / cc 区域（刀2 / #223）。
 *
 * ★ **本文件是出厂区域预设的落盘数据（刀2 / #223 产出）；生成脚本已于刀3 删除，请勿手改。**
 *   它是**唯一真值**：10 套出厂预设的有效值由它算出（`effectivePresetTheme`）——
 *   改这里的任何一个值，等于改掉所有引用它的预设。历史来源见 `.agents/records/issue-223-factory-zone-presets-as-data.md`。
 * 值 = 生成时刻的 `pickZoneFields(GLOBAL_PRESETS[来源].theme, 'cc')`，逐字段照抄
 * （含终端补全烘入的默认值；cc 区含 ccLayout/ccHidden 两个元件名单字段）。
 */
import type { ZonePresetEntry } from '../zonePresetPool.ts'

export const FACTORY_TERMINAL_CC: readonly ZonePresetEntry[] = [
  {
    id: 'claude',
    mode: 'terminal',
    zone: 'cc',
    label: 'Claude 风格',
    origin: 'factory',
    source: { presetName: 'claude' },
    values: {
      ccHeight: 76,
      ccMarginX: 15,
      ccMarginBottom: 15,
      ccRadius: 25,
      ccBg: "#000000",
      ccSurfaceOpacity: 1,
      ccBgImage: "",
      ccLayout: {
        "version": 9,
        "placements": {
          "input": {
            "slot": "input",
            "order": 0,
            "offsetX": 0,
            "offsetY": 0
          },
          "model": {
            "slot": "status-secondary",
            "order": 2,
            "offsetX": 0,
            "offsetY": 0
          },
          "reasoning": {
            "slot": "status-secondary",
            "order": 3,
            "offsetX": 0,
            "offsetY": 0
          },
          "mode": {
            "slot": "status-secondary",
            "order": 4,
            "offsetX": 0,
            "offsetY": 0
          },
          "tokens": {
            "slot": "status-secondary",
            "order": 5,
            "offsetX": 0,
            "offsetY": 0
          },
          "cc-command-hint": {
            "order": 5,
            "offsetX": 0,
            "offsetY": 0
          },
          "cc-send-button": {
            "slot": "actions",
            "order": 0,
            "offsetX": 0,
            "offsetY": 0
          }
        }
      },
      ccHidden: [
        "cc-send-button"
      ],
      inputOffsetTop: 10,
      inputHeight: 40,
      inputMarginX: 10,
      inputSurfaceBg: "#FFFFFF",
      inputSurfaceOpacity: 1,
      inputFocusRingEnabled: "shown",
      inputFocusRingColor: "var(--accent)",
      inputHighlightOpacity: 0,
      inputShadowEnabled: "shown",
      inputBg: "transparent",
      inputBgImage: "",
      inputTextColor: "#FFFFFF",
      inputPlaceholder: "#999999",
      sendButtonColor: "#000000",
      sendButtonRadius: "0.5",
      sendButtonBorderColor: "white",
      sendButtonIcon: "arrow",
      sendButtonIconGenerating: "square",
      sendButtonIconRound: "on",
      sendButtonIconColor: "white",
      inputBorderColor: "",
      inputFocusBorder: "#505050",
      inputBorder: "transparent",
      inputBorderWidth: 1,
      inputBorderOpacity: 0,
      inputRadius: 20,
      inputFontSize: 15,
      inputLineHeight: "1",
      inputMinHeight: 56,
      inputMode: "cli",
      inputVariant: "cli",
      inputShowPlaceholder: true,
      inputShowHistoryHint: true,
      inputSubmitButtonMode: "inline",
      cliLineWidth: 2,
      cliLineColor: "#888888",
      cliTextColor: "#FFFFFF",
      cliPromptColor: "#999999",
      cliLinePadding: 3,
      cliContentOffsetY: 0,
      cliHintMode: "full",
      ccHintFontSize: 16,
      footerLayout: "peri",
      cliOverflowMode: "fixed-scroll",
      pillText: "rgba(205,214,244,0.6)",
      prismOnColor: "#4ade80",
      modelSwitchMode: "cycle",
      modelBgColor: "white",
      modelWidth: 120,
      modelHeight: 28,
      modelRadius: 0,
      modelFontSize: 12,
      modelTextColor: "black",
      reasoningSwitchMode: "menu",
      reasoningBgColor: "white",
      reasoningWidth: 120,
      reasoningHeight: 28,
      reasoningRadius: 0,
      reasoningFontSize: 12,
      reasoningTextColor: "black",
      permissionSwitchMode: "cycle",
      permissionBgColor: "white",
      permissionWidth: 120,
      permissionHeight: 28,
      permissionRadius: 0,
      permissionFontSize: 12,
      permissionTextColor: "mode",
      sendVariant: "minimal",
      modeAutoColor: "#FFC107",
      modeEditColor: "#A2A9E4",
    },
  },
  {
    id: 'nord',
    mode: 'terminal',
    zone: 'cc',
    label: 'Nord Frost',
    origin: 'factory',
    source: { presetName: 'nord' },
    values: {
      ccHeight: 96,
      ccMarginX: 15,
      ccMarginBottom: 15,
      ccRadius: 25,
      ccBg: "#252838",
      ccSurfaceOpacity: 1,
      ccBgImage: "",
      ccLayout: {
        "version": 9,
        "placements": {
          "input": {
            "slot": "input",
            "order": 0,
            "offsetX": 0,
            "offsetY": 0
          },
          "model": {
            "slot": "status-secondary",
            "order": 2,
            "offsetX": 0,
            "offsetY": 0
          },
          "reasoning": {
            "slot": "status-secondary",
            "order": 3,
            "offsetX": 0,
            "offsetY": 0
          },
          "mode": {
            "slot": "status-secondary",
            "order": 4,
            "offsetX": 0,
            "offsetY": 0
          },
          "tokens": {
            "slot": "status-secondary",
            "order": 5,
            "offsetX": 0,
            "offsetY": 0
          },
          "cc-command-hint": {
            "order": 5,
            "offsetX": 0,
            "offsetY": 0
          },
          "cc-send-button": {
            "slot": "actions",
            "order": 0,
            "offsetX": 0,
            "offsetY": 0
          }
        }
      },
      ccHidden: [
        "cc-send-button"
      ],
      inputOffsetTop: 10,
      inputHeight: 40,
      inputMarginX: 10,
      inputSurfaceBg: "#FFFFFF",
      inputSurfaceOpacity: 1,
      inputFocusRingEnabled: "shown",
      inputFocusRingColor: "var(--accent)",
      inputHighlightOpacity: 0,
      inputShadowEnabled: "shown",
      inputBg: "rgba(255,255,255,0.03)",
      inputBgImage: "",
      inputTextColor: "#e5e9f0",
      inputPlaceholder: "rgba(229,233,240,0.20)",
      sendButtonColor: "#000000",
      sendButtonRadius: "0.5",
      sendButtonBorderColor: "white",
      sendButtonIcon: "arrow",
      sendButtonIconGenerating: "square",
      sendButtonIconRound: "on",
      sendButtonIconColor: "white",
      inputBorderColor: "",
      inputFocusBorder: "rgba(136,192,208,0.45)",
      inputBorder: "transparent",
      inputBorderWidth: 1,
      inputBorderOpacity: 0,
      inputRadius: 20,
      inputFontSize: 15,
      inputLineHeight: "1",
      inputMinHeight: 52,
      inputMode: "cli",
      inputVariant: "cli",
      inputShowPlaceholder: true,
      inputShowHistoryHint: true,
      inputSubmitButtonMode: "inline",
      cliLineWidth: 2,
      cliLineColor: "#7f8ea3",
      cliTextColor: "#e5e9f0",
      cliPromptColor: "#9aa7bd",
      cliLinePadding: 3,
      cliContentOffsetY: 0,
      cliHintMode: "compact",
      ccHintFontSize: 16,
      footerLayout: "free",
      cliOverflowMode: "fixed-scroll",
      pillText: "rgba(136,192,208,0.75)",
      prismOnColor: "#a3be8c",
      modelSwitchMode: "cycle",
      modelBgColor: "white",
      modelWidth: 120,
      modelHeight: 28,
      modelRadius: 0,
      modelFontSize: 12,
      modelTextColor: "black",
      reasoningSwitchMode: "menu",
      reasoningBgColor: "white",
      reasoningWidth: 120,
      reasoningHeight: 28,
      reasoningRadius: 0,
      reasoningFontSize: 12,
      reasoningTextColor: "black",
      permissionSwitchMode: "menu",
      permissionBgColor: "white",
      permissionWidth: 120,
      permissionHeight: 28,
      permissionRadius: 0,
      permissionFontSize: 12,
      permissionTextColor: "mode",
      sendVariant: "icon",
      modeAutoColor: "#ebcb8b",
      modeEditColor: "#88c0d0",
    },
  },
  {
    id: 'tokyo',
    mode: 'terminal',
    zone: 'cc',
    label: 'Tokyo Night',
    origin: 'factory',
    source: { presetName: 'tokyo' },
    values: {
      ccHeight: 96,
      ccMarginX: 15,
      ccMarginBottom: 15,
      ccRadius: 25,
      ccBg: "#1a1b26",
      ccSurfaceOpacity: 1,
      ccBgImage: "",
      ccLayout: {
        "version": 9,
        "placements": {
          "input": {
            "slot": "input",
            "order": 0,
            "offsetX": 0,
            "offsetY": 0
          },
          "model": {
            "slot": "status-secondary",
            "order": 2,
            "offsetX": 0,
            "offsetY": 0
          },
          "reasoning": {
            "slot": "status-secondary",
            "order": 3,
            "offsetX": 0,
            "offsetY": 0
          },
          "mode": {
            "slot": "status-secondary",
            "order": 4,
            "offsetX": 0,
            "offsetY": 0
          },
          "tokens": {
            "slot": "status-secondary",
            "order": 5,
            "offsetX": 0,
            "offsetY": 0
          },
          "cc-command-hint": {
            "order": 5,
            "offsetX": 0,
            "offsetY": 0
          },
          "cc-send-button": {
            "slot": "actions",
            "order": 0,
            "offsetX": 0,
            "offsetY": 0
          }
        }
      },
      ccHidden: [
        "cc-send-button"
      ],
      inputOffsetTop: 10,
      inputHeight: 40,
      inputMarginX: 10,
      inputSurfaceBg: "#FFFFFF",
      inputSurfaceOpacity: 1,
      inputFocusRingEnabled: "shown",
      inputFocusRingColor: "var(--accent)",
      inputHighlightOpacity: 0,
      inputShadowEnabled: "shown",
      inputBg: "transparent",
      inputBgImage: "",
      inputTextColor: "#c0caf5",
      inputPlaceholder: "#565f89",
      sendButtonColor: "#000000",
      sendButtonRadius: "0.5",
      sendButtonBorderColor: "white",
      sendButtonIcon: "arrow",
      sendButtonIconGenerating: "square",
      sendButtonIconRound: "on",
      sendButtonIconColor: "white",
      inputBorderColor: "",
      inputFocusBorder: "#7aa2f7",
      inputBorder: "transparent",
      inputBorderWidth: 1,
      inputBorderOpacity: 0,
      inputRadius: 20,
      inputFontSize: 15,
      inputLineHeight: "1",
      inputMinHeight: 56,
      inputMode: "cli",
      inputVariant: "cli",
      inputShowPlaceholder: true,
      inputShowHistoryHint: true,
      inputSubmitButtonMode: "inline",
      cliLineWidth: 2,
      cliLineColor: "#565f89",
      cliTextColor: "#c0caf5",
      cliPromptColor: "#7f89b0",
      cliLinePadding: 3,
      cliContentOffsetY: 0,
      cliHintMode: "compact",
      ccHintFontSize: 16,
      footerLayout: "free",
      cliOverflowMode: "fixed-scroll",
      pillText: "#a9b1d6",
      prismOnColor: "#9ece6a",
      modelSwitchMode: "cycle",
      modelBgColor: "white",
      modelWidth: 120,
      modelHeight: 28,
      modelRadius: 0,
      modelFontSize: 12,
      modelTextColor: "black",
      reasoningSwitchMode: "menu",
      reasoningBgColor: "white",
      reasoningWidth: 120,
      reasoningHeight: 28,
      reasoningRadius: 0,
      reasoningFontSize: 12,
      reasoningTextColor: "black",
      permissionSwitchMode: "cycle",
      permissionBgColor: "white",
      permissionWidth: 120,
      permissionHeight: 28,
      permissionRadius: 0,
      permissionFontSize: 12,
      permissionTextColor: "mode",
      sendVariant: "minimal",
      modeAutoColor: "#e0af68",
      modeEditColor: "#7aa2f7",
    },
  },
  {
    id: 'amber',
    mode: 'terminal',
    zone: 'cc',
    label: 'Amber CRT',
    origin: 'factory',
    source: { presetName: 'amber' },
    values: {
      ccHeight: 96,
      ccMarginX: 15,
      ccMarginBottom: 15,
      ccRadius: 25,
      ccBg: "#120b00",
      ccSurfaceOpacity: 1,
      ccBgImage: "",
      ccLayout: {
        "version": 9,
        "placements": {
          "input": {
            "slot": "input",
            "order": 0,
            "offsetX": 0,
            "offsetY": 0
          },
          "model": {
            "slot": "status-secondary",
            "order": 2,
            "offsetX": 0,
            "offsetY": 0
          },
          "reasoning": {
            "slot": "status-secondary",
            "order": 3,
            "offsetX": 0,
            "offsetY": 0
          },
          "mode": {
            "slot": "status-secondary",
            "order": 4,
            "offsetX": 0,
            "offsetY": 0
          },
          "tokens": {
            "slot": "status-secondary",
            "order": 5,
            "offsetX": 0,
            "offsetY": 0
          },
          "cc-command-hint": {
            "order": 5,
            "offsetX": 0,
            "offsetY": 0
          },
          "cc-send-button": {
            "slot": "actions",
            "order": 0,
            "offsetX": 0,
            "offsetY": 0
          }
        }
      },
      ccHidden: [
        "cc-send-button"
      ],
      inputOffsetTop: 10,
      inputHeight: 40,
      inputMarginX: 10,
      inputSurfaceBg: "#FFFFFF",
      inputSurfaceOpacity: 1,
      inputFocusRingEnabled: "shown",
      inputFocusRingColor: "var(--accent)",
      inputHighlightOpacity: 0,
      inputShadowEnabled: "shown",
      inputBg: "transparent",
      inputBgImage: "",
      inputTextColor: "#ffcc55",
      inputPlaceholder: "#7a5200",
      sendButtonColor: "#000000",
      sendButtonRadius: "0.5",
      sendButtonBorderColor: "white",
      sendButtonIcon: "arrow",
      sendButtonIconGenerating: "square",
      sendButtonIconRound: "on",
      sendButtonIconColor: "white",
      inputBorderColor: "",
      inputFocusBorder: "#ffb000",
      inputBorder: "transparent",
      inputBorderWidth: 1,
      inputBorderOpacity: 0,
      inputRadius: 20,
      inputFontSize: 15,
      inputLineHeight: "1",
      inputMinHeight: 56,
      inputMode: "cli",
      inputVariant: "cli",
      inputShowPlaceholder: true,
      inputShowHistoryHint: true,
      inputSubmitButtonMode: "inline",
      cliLineWidth: 2,
      cliLineColor: "#9b6b00",
      cliTextColor: "#ffcc55",
      cliPromptColor: "#cc8c00",
      cliLinePadding: 3,
      cliContentOffsetY: 0,
      cliHintMode: "compact",
      ccHintFontSize: 16,
      footerLayout: "free",
      cliOverflowMode: "fixed-scroll",
      pillText: "#cc8c00",
      prismOnColor: "#ffc24b",
      modelSwitchMode: "cycle",
      modelBgColor: "white",
      modelWidth: 120,
      modelHeight: 28,
      modelRadius: 0,
      modelFontSize: 12,
      modelTextColor: "black",
      reasoningSwitchMode: "menu",
      reasoningBgColor: "white",
      reasoningWidth: 120,
      reasoningHeight: 28,
      reasoningRadius: 0,
      reasoningFontSize: 12,
      reasoningTextColor: "black",
      permissionSwitchMode: "cycle",
      permissionBgColor: "white",
      permissionWidth: 120,
      permissionHeight: 28,
      permissionRadius: 0,
      permissionFontSize: 12,
      permissionTextColor: "mode",
      sendVariant: "minimal",
      modeAutoColor: "#ffb000",
      modeEditColor: "#ffcc55",
    },
  },
  {
    id: 'matrix',
    mode: 'terminal',
    zone: 'cc',
    label: 'Matrix 磷绿',
    origin: 'factory',
    source: { presetName: 'matrix' },
    values: {
      ccHeight: 96,
      ccMarginX: 15,
      ccMarginBottom: 15,
      ccRadius: 25,
      ccBg: "#050f05",
      ccSurfaceOpacity: 1,
      ccBgImage: "",
      ccLayout: {
        "version": 9,
        "placements": {
          "input": {
            "slot": "input",
            "order": 0,
            "offsetX": 0,
            "offsetY": 0
          },
          "model": {
            "slot": "status-secondary",
            "order": 2,
            "offsetX": 0,
            "offsetY": 0
          },
          "reasoning": {
            "slot": "status-secondary",
            "order": 3,
            "offsetX": 0,
            "offsetY": 0
          },
          "mode": {
            "slot": "status-secondary",
            "order": 4,
            "offsetX": 0,
            "offsetY": 0
          },
          "tokens": {
            "slot": "status-secondary",
            "order": 5,
            "offsetX": 0,
            "offsetY": 0
          },
          "cc-command-hint": {
            "order": 5,
            "offsetX": 0,
            "offsetY": 0
          },
          "cc-send-button": {
            "slot": "actions",
            "order": 0,
            "offsetX": 0,
            "offsetY": 0
          }
        }
      },
      ccHidden: [
        "cc-send-button"
      ],
      inputOffsetTop: 10,
      inputHeight: 40,
      inputMarginX: 10,
      inputSurfaceBg: "#FFFFFF",
      inputSurfaceOpacity: 1,
      inputFocusRingEnabled: "shown",
      inputFocusRingColor: "var(--accent)",
      inputHighlightOpacity: 0,
      inputShadowEnabled: "shown",
      inputBg: "transparent",
      inputBgImage: "",
      inputTextColor: "#b8ffb8",
      inputPlaceholder: "#1a5c1a",
      sendButtonColor: "#000000",
      sendButtonRadius: "0.5",
      sendButtonBorderColor: "white",
      sendButtonIcon: "arrow",
      sendButtonIconGenerating: "square",
      sendButtonIconRound: "on",
      sendButtonIconColor: "white",
      inputBorderColor: "",
      inputFocusBorder: "#39ff14",
      inputBorder: "transparent",
      inputBorderWidth: 1,
      inputBorderOpacity: 0,
      inputRadius: 20,
      inputFontSize: 15,
      inputLineHeight: "1",
      inputMinHeight: 56,
      inputMode: "cli",
      inputVariant: "cli",
      inputShowPlaceholder: true,
      inputShowHistoryHint: true,
      inputSubmitButtonMode: "inline",
      cliLineWidth: 2,
      cliLineColor: "#1a5c1a",
      cliTextColor: "#b8ffb8",
      cliPromptColor: "#39ff14",
      cliLinePadding: 3,
      cliContentOffsetY: 0,
      cliHintMode: "compact",
      ccHintFontSize: 16,
      footerLayout: "free",
      cliOverflowMode: "fixed-scroll",
      pillText: "#39ff14",
      prismOnColor: "#39ff14",
      modelSwitchMode: "cycle",
      modelBgColor: "white",
      modelWidth: 120,
      modelHeight: 28,
      modelRadius: 0,
      modelFontSize: 12,
      modelTextColor: "black",
      reasoningSwitchMode: "menu",
      reasoningBgColor: "white",
      reasoningWidth: 120,
      reasoningHeight: 28,
      reasoningRadius: 0,
      reasoningFontSize: 12,
      reasoningTextColor: "black",
      permissionSwitchMode: "cycle",
      permissionBgColor: "white",
      permissionWidth: 120,
      permissionHeight: 28,
      permissionRadius: 0,
      permissionFontSize: 12,
      permissionTextColor: "mode",
      sendVariant: "minimal",
      modeAutoColor: "#39ff14",
      modeEditColor: "#7fff00",
    },
  },
]

// 本文件 5 条 / 415 个字段值
