/**
 * 区域层 · 出厂区域预设数据 —— terminal 桶 / global 区域（刀2 / #223）。
 *
 * ★ **本文件是出厂区域预设的落盘数据（刀2 / #223 产出）；生成脚本已于刀3 删除，请勿手改。**
 *   它是**唯一真值**：10 套出厂预设的有效值由它算出（`effectivePresetTheme`）——
 *   改这里的任何一个值，等于改掉所有引用它的预设。历史来源见 `.agents/records/issue-223-factory-zone-presets-as-data.md`。
 * 值 = 生成时刻的 `pickZoneFields(GLOBAL_PRESETS[来源].theme, 'global')`，逐字段照抄
 * （含终端补全烘入的默认值；cc 区含 ccLayout/ccHidden 两个元件名单字段）。
 */
import type { ZonePresetEntry } from '../zonePresetPool.ts'

export const FACTORY_TERMINAL_GLOBAL: readonly ZonePresetEntry[] = [
  {
    id: 'claude',
    mode: 'terminal',
    zone: 'global',
    label: 'Claude 风格',
    origin: 'factory',
    source: { presetName: 'claude' },
    values: {
      accent: "#D77757",
      transparency: 1,
      bgBlur: 0,
      globalFont: "system",
      codeFont: "mono",
      globalFontSize: 15,
      globalBgImage: "",
      globalBgColor: "#000000",
      uiScheme: "dark",
      titlebarBg: "#000000",
      titlebarTextColor: "#FFFFFF",
      userName: "",
      userPrefix: "❯",
      userColor: "#D77757",
      showTabBar: true,
      showSidebar: true,
      showPet: true,
    },
  },
  {
    id: 'nord',
    mode: 'terminal',
    zone: 'global',
    label: 'Nord Frost',
    origin: 'factory',
    source: { presetName: 'nord' },
    values: {
      accent: "#88c0d0",
      transparency: 0.96,
      bgBlur: 12,
      globalFont: "system",
      codeFont: "mono",
      globalFontSize: 15,
      globalBgImage: "",
      globalBgColor: "#1e2130",
      uiScheme: "dark",
      titlebarBg: "#252838",
      titlebarTextColor: "#e5e9f0",
      userName: "",
      userPrefix: "❯",
      userColor: "#88c0d0",
      showTabBar: true,
      showSidebar: true,
      showPet: true,
    },
  },
  {
    id: 'tokyo',
    mode: 'terminal',
    zone: 'global',
    label: 'Tokyo Night',
    origin: 'factory',
    source: { presetName: 'tokyo' },
    values: {
      accent: "#7aa2f7",
      transparency: 1,
      bgBlur: 0,
      globalFont: "system",
      codeFont: "mono",
      globalFontSize: 15,
      globalBgImage: "",
      globalBgColor: "#1a1b26",
      uiScheme: "dark",
      titlebarBg: "#16161e",
      titlebarTextColor: "#c0caf5",
      userName: "",
      userPrefix: "❯",
      userColor: "#bb9af7",
      showTabBar: true,
      showSidebar: true,
      showPet: true,
    },
  },
  {
    id: 'amber',
    mode: 'terminal',
    zone: 'global',
    label: 'Amber CRT',
    origin: 'factory',
    source: { presetName: 'amber' },
    values: {
      accent: "#ffb000",
      transparency: 1,
      bgBlur: 0,
      globalFont: "system",
      codeFont: "mono",
      globalFontSize: 15,
      globalBgImage: "",
      globalBgColor: "#120b00",
      uiScheme: "dark",
      titlebarBg: "#120b00",
      titlebarTextColor: "#ffcc55",
      userName: "",
      userPrefix: ">",
      userColor: "#ffb000",
      showTabBar: true,
      showSidebar: true,
      showPet: true,
    },
  },
  {
    id: 'matrix',
    mode: 'terminal',
    zone: 'global',
    label: 'Matrix 磷绿',
    origin: 'factory',
    source: { presetName: 'matrix' },
    values: {
      accent: "#39ff14",
      transparency: 1,
      bgBlur: 0,
      globalFont: "system",
      codeFont: "mono",
      globalFontSize: 15,
      globalBgImage: "",
      globalBgColor: "#050f05",
      uiScheme: "dark",
      titlebarBg: "#050f05",
      titlebarTextColor: "#39ff14",
      userName: "",
      userPrefix: "❯",
      userColor: "#7fff00",
      showTabBar: true,
      showSidebar: true,
      showPet: true,
    },
  },
]

// 本文件 5 条 / 85 个字段值
