import type { PresentationProfileContribution } from '../../../plugin-runtime/presentation/presentationProfileTypes.ts'

const EXECUTION_SURFACE_TOKENS = Object.freeze({
  msgStyle: 'bubble', messageLayout: 'bubble', chatFont: 'system', msgFont: 'system', msgLineHeight: 1.62,
  messageUserBg: 'rgba(59,130,246,0.12)', messageAssistantBg: 'rgba(148,163,184,0.08)',
  messageReasoningBg: 'rgba(99,102,241,0.06)', messageBorderColor: 'rgba(99,102,241,0.20)', messageRadius: 12,
  inputMode: 'default', inputVariant: 'composer', inputBg: 'rgba(148,163,184,0.09)',
  inputBorderColor: 'rgba(148,163,184,0.24)', inputFocusBorder: 'rgba(99,102,241,0.72)',
  inputRadius: 12, inputFocusRingWidth: 3, ccVariant: 'glass', assistantDot: true,
  toolConnectorMode: 'follow', toolConnectorStyle: 'solid', footerLayout: 'peri', cliHintMode: 'hidden',
})

const AGENT_COMMAND_KIND_TOKENS = Object.freeze({
  'content.plan': { density: 'compact', defaultExpanded: true, collapseCompleted: false, nodeGlyph: 'status', connectorStyle: 'solid', indent: 18 },
  'activity.subagent': { density: 'compact', viewMode: 'cards', identityMarker: 'avatar', showIdentity: true, showAggregate: true, defaultExpandedDepth: 1, cardWidth: 1200, indent: 0 },
  'activity.delegation': { density: 'compact', viewMode: 'cards', identityMarker: 'glyph', showIdentity: true, showAggregate: true, defaultExpandedDepth: 1, cardWidth: 1200, indent: 0 },
  'activity.team': { density: 'compact', viewMode: 'cards', identityMarker: 'avatar', showIdentity: true, showAggregate: true, defaultExpandedDepth: 1, cardWidth: 1200, indent: 0 },
  'activity.workflow': { density: 'compact', workflowLayout: 'lanes', workflowConnector: true, collapseCompleted: false, indent: 14 },
  'activity.workflow-phase': { density: 'compact', workflowLayout: 'lanes', workflowConnector: true, collapseCompleted: false, indent: 14 },
  'activity.workflow-agent': { density: 'compact', workflowLayout: 'lanes', workflowConnector: true, collapseCompleted: false, indent: 14 },
  'activity.background-task': { density: 'compact', workflowLayout: 'lanes', workflowConnector: true, collapseCompleted: false, indent: 14 },
})

const AGENT_MAP_KIND_TOKENS = Object.freeze({
  'content.plan': { density: 'comfortable', defaultExpanded: true, collapseCompleted: true, nodeGlyph: 'dot', connectorStyle: 'dashed', indent: 24 },
  'activity.subagent': { density: 'comfortable', viewMode: 'tree', identityMarker: 'avatar', treeLineStyle: 'solid', showIdentity: true, showAggregate: true, defaultExpandedDepth: 2, indent: 28 },
  'activity.delegation': { density: 'comfortable', viewMode: 'tree', identityMarker: 'glyph', treeLineStyle: 'dashed', showIdentity: true, showAggregate: true, defaultExpandedDepth: 2, indent: 28 },
  'activity.team': { density: 'comfortable', viewMode: 'tree', identityMarker: 'avatar', treeLineStyle: 'solid', showIdentity: true, showAggregate: true, defaultExpandedDepth: 2, indent: 28 },
  'activity.workflow': { density: 'comfortable', workflowLayout: 'timeline', workflowConnector: true, collapseCompleted: true, indent: 24 },
  'activity.workflow-phase': { density: 'comfortable', workflowLayout: 'timeline', workflowConnector: true, collapseCompleted: true, indent: 24 },
  'activity.workflow-agent': { density: 'comfortable', workflowLayout: 'timeline', workflowConnector: true, collapseCompleted: true, indent: 24 },
  'activity.background-task': { density: 'comfortable', workflowLayout: 'timeline', workflowConnector: true, collapseCompleted: true, indent: 24 },
})

const FOCUS_FLOW_KIND_TOKENS = Object.freeze({
  'content.plan': { density: 'compact', defaultExpanded: false, collapseCompleted: true, nodeGlyph: 'none', connectorStyle: 'none', showPriority: false, indent: 12 },
  'activity.subagent': { density: 'compact', viewMode: 'cards', identityMarker: 'none', showIdentity: false, showAggregate: false, defaultExpandedDepth: 0, cardWidth: 980, indent: 0 },
  'activity.delegation': { density: 'compact', viewMode: 'cards', identityMarker: 'none', showIdentity: false, showAggregate: false, defaultExpandedDepth: 0, cardWidth: 980, indent: 0 },
  'activity.team': { density: 'compact', viewMode: 'cards', identityMarker: 'none', showIdentity: false, showAggregate: false, defaultExpandedDepth: 0, cardWidth: 980, indent: 0 },
  'activity.workflow': { density: 'compact', workflowLayout: 'list', workflowConnector: false, collapseCompleted: true, animateProgress: false, indent: 0 },
  'activity.workflow-phase': { density: 'compact', workflowLayout: 'list', workflowConnector: false, collapseCompleted: true, animateProgress: false, indent: 0 },
  'activity.workflow-agent': { density: 'compact', workflowLayout: 'list', workflowConnector: false, collapseCompleted: true, animateProgress: false, indent: 0 },
  'activity.background-task': { density: 'compact', workflowLayout: 'list', workflowConnector: false, collapseCompleted: true, animateProgress: false, indent: 0 },
})

export const BUILTIN_PRESENTATION_PROFILES: readonly PresentationProfileContribution[] = Object.freeze([
  {
    id: 'builtin.presentation.modern-gui',
    label: '现代工作台',
    description: '图形化消息、分层工具卡和现代编辑器输入。',
    family: 'gui',
    interfaceMode: 'modern-gui',
    order: 50,
    tokens: {
      msgStyle: 'bubble', messageLayout: 'bubble', chatFont: 'system', msgFont: 'system',
      msgLineHeight: 1.65, messageUserBg: 'rgba(59,130,246,0.14)', messageAssistantBg: 'rgba(148,163,184,0.10)',
      messageReasoningBg: 'rgba(99,102,241,0.07)', messageBorderColor: 'rgba(99,102,241,0.20)', messageRadius: 16,
      inputMode: 'default', inputVariant: 'composer', inputBg: 'rgba(148,163,184,0.10)',
      inputBorderColor: 'rgba(148,163,184,0.26)', inputFocusBorder: 'rgba(99,102,241,0.74)', inputRadius: 16, inputFocusRingWidth: 4,
      ccVariant: 'glass', assistantDot: true, assistantDotGlyph: '◆', toolIndicator: '◆', toolIndicatorGlow: 3,
      toolConnectorMode: 'none', spinnerFramePreset: 'orbit', spinnerVerbSet: 'analysis', cliHintMode: 'hidden', footerLayout: 'peri',
    },
    assets: { assistantGlyph: '◆', runningGlyph: '▶', completedGlyph: '✓', failedGlyph: '!' },
  },
  {
    id: 'builtin.presentation.terminal-classic',
    label: '终端经典',
    description: '紧凑命令记录流、可读正文、CLI 输入和克制的工具状态。',
    family: 'terminal',
    order: 100,
    tokens: {
      msgStyle: 'terminal', messageLayout: 'classic', chatFont: 'mono', msgFont: 'system',
      msgLineHeight: 1.55, inputMode: 'cli', inputVariant: 'cli', inputBg: 'rgba(0,0,0,0.02)',
      inputBorderColor: '', inputFocusBorder: 'rgba(0,0,0,0.22)', inputRadius: 0, inputFocusRingWidth: 0,
      ccVariant: 'terminal',
      assistantDot: false, toolIndicator: '●', toolIndicatorRun: 'circle', toolIndicatorOk: 'circle', toolIndicatorErr: 'circle', toolIndicatorGlow: 0,
      toolConnectorMode: 'none', spinnerFramePreset: 'ascii-line', spinnerVerbSet: 'engineering',
      cliHintMode: 'compact', footerLayout: 'free',
    },
    assets: { promptGlyph: '❯', runningGlyph: '●', completedGlyph: '●', failedGlyph: '●' },
  },
  {
    id: 'builtin.presentation.terminal-modern',
    label: '现代终端',
    description: '强化运行态、连接线与焦点辉光，适合长工具链。',
    family: 'terminal',
    order: 110,
    tokens: {
      msgStyle: 'bubble', messageLayout: 'classic', chatFont: 'mono', msgFont: 'mono',
      msgLineHeight: 1.65, messageUserBg: 'rgba(59,130,246,0.14)', messageAssistantBg: 'rgba(127,127,127,0.08)',
      messageReasoningBg: 'rgba(59,130,246,0.05)', messageBorderColor: 'rgba(59,130,246,0.28)', messageRadius: 8,
      inputMode: 'default', inputVariant: 'command', inputBg: 'rgba(59,130,246,0.08)',
      inputBorderColor: 'rgba(59,130,246,0.32)', inputFocusBorder: 'rgba(59,130,246,0.82)', inputRadius: 8, inputFocusRingWidth: 3,
      ccVariant: 'glass',
      assistantDot: true, assistantDotGlyph: '◆', toolIndicator: '◆', toolIndicatorGlow: 5,
      toolConnectorMode: 'follow', toolConnectorStyle: 'pulse', toolConnectorWidth: 2,
      spinnerFramePreset: 'scan', spinnerVerbSet: 'analysis', cliHintMode: 'full', footerLayout: 'peri',
    },
    assets: { promptGlyph: '❯', assistantGlyph: '◆', runningGlyph: '▶', completedGlyph: '◆', failedGlyph: '■' },
  },
  {
    id: 'builtin.presentation.paper-low-contrast',
    label: '低对比纸张',
    description: '自然语言使用阅读排版，保留命令语义并降低视觉噪声。',
    family: 'reading',
    order: 120,
    tokens: {
      msgStyle: 'bubble', messageLayout: 'claude', chatFont: 'serif', msgFont: 'serif',
      msgLineHeight: 1.7, messageUserBg: 'rgba(163,128,72,0.12)', messageAssistantBg: 'rgba(163,128,72,0.05)',
      messageReasoningBg: 'rgba(163,128,72,0.035)', messageBorderColor: 'rgba(128,102,63,0.22)', messageRadius: 4,
      inputMode: 'default', inputVariant: 'composer', inputBg: 'rgba(163,128,72,0.06)',
      inputBorderColor: 'rgba(128,102,63,0.24)', inputFocusBorder: 'rgba(128,102,63,0.52)', inputRadius: 4, inputFocusRingWidth: 2,
      ccVariant: 'pill',
      assistantDot: true, assistantDotGlyph: '●', toolIndicator: '▶', toolIndicatorGlow: 2,
      toolConnectorMode: 'follow', toolConnectorStyle: 'solid', spinnerFramePreset: 'braille',
      spinnerVerbSet: 'zh', cliHintMode: 'compact', footerLayout: 'peri',
    },
    assets: { promptGlyph: '›', assistantGlyph: '●', runningGlyph: '▶', completedGlyph: '✓', failedGlyph: '!' },
  },
  {
    id: 'builtin.presentation.console-glass',
    label: '玻璃控制台',
    description: '柔和玻璃工作台；自然语言使用 GUI 排版，工具输出保持终端语义。',
    family: 'hybrid',
    order: 200,
    tokens: {
      msgStyle: 'bubble', messageLayout: 'bubble', chatFont: 'system', msgFont: 'system',
      msgLineHeight: 1.75, messageUserBg: 'rgba(99,102,241,0.16)', messageAssistantBg: 'rgba(148,163,184,0.12)',
      messageReasoningBg: 'rgba(99,102,241,0.07)', messageBorderColor: 'rgba(148,163,184,0.28)', messageRadius: 18,
      inputMode: 'default', inputVariant: 'composer', inputBg: 'rgba(148,163,184,0.12)',
      inputBorderColor: 'rgba(148,163,184,0.30)', inputFocusBorder: 'rgba(99,102,241,0.72)', inputRadius: 16, inputFocusRingWidth: 4,
      ccVariant: 'glass',
      assistantDot: true, assistantDotGlyph: '✦', toolIndicator: '✦', toolIndicatorGlow: 3,
      toolConnectorMode: 'follow', toolConnectorStyle: 'solid', spinnerFramePreset: 'orbit',
      spinnerVerbSet: 'zh', cliHintMode: 'hidden', footerLayout: 'peri',
    },
    assets: { assistantGlyph: '✦', runningGlyph: '✦', completedGlyph: '✓', failedGlyph: '!' },
  },
  {
    id: 'builtin.presentation.agent-command',
    label: 'Agent 指挥台',
    description: '展开计划与执行统计，用紧凑卡片同时观察多代理协作。',
    family: 'gui', interfaceMode: 'modern-gui', order: 60,
    tokens: { ...EXECUTION_SURFACE_TOKENS, assistantDotGlyph: '◆', toolIndicator: '◆', toolIndicatorGlow: 3, spinnerFramePreset: 'scan', spinnerVerbSet: 'engineering' },
    kindTokens: AGENT_COMMAND_KIND_TOKENS,
    assets: { assistantGlyph: '◈', runningGlyph: '●', completedGlyph: '✓', failedGlyph: '!' },
  },
  {
    id: 'builtin.presentation.agent-map',
    label: 'Agent 关系图',
    description: '强调父子缩进、连接线和身份头像，适合追踪委派链。',
    family: 'gui', interfaceMode: 'modern-gui', order: 70,
    tokens: { ...EXECUTION_SURFACE_TOKENS, assistantDotGlyph: '✦', toolIndicator: '✦', toolIndicatorGlow: 2, spinnerFramePreset: 'orbit', spinnerVerbSet: 'analysis' },
    kindTokens: AGENT_MAP_KIND_TOKENS,
    assets: { assistantGlyph: '◇', runningGlyph: '◐', completedGlyph: '✓', failedGlyph: '×' },
  },
  {
    id: 'builtin.presentation.focus-flow',
    label: '专注流程',
    description: '收起已完成内容与次要统计，只保留当前任务和关键输出。',
    family: 'reading', interfaceMode: 'modern-gui', order: 80,
    tokens: { ...EXECUTION_SURFACE_TOKENS, messageLayout: 'claude', messageRadius: 6, assistantDotGlyph: '●', toolIndicator: '▶', toolIndicatorGlow: 0, spinnerFramePreset: 'braille', spinnerVerbSet: 'zh' },
    kindTokens: FOCUS_FLOW_KIND_TOKENS,
    assets: { assistantGlyph: '•', runningGlyph: '›', completedGlyph: '✓', failedGlyph: '!' },
  },
])
