/** 预设层 · 内置预设数据：RAW_GLOBAL_PRESETS → GLOBAL_PRESETS。 */

import type { GlobalPreset, PresetInterfaceMode, PresetName } from './types.ts'
import type { ThemeSettings } from '../store.ts'
import { completeTerminalPreset } from './completion.ts'

const RAW_GLOBAL_PRESETS: GlobalPreset[] = [
  {
    name: 'claude',
    interfaceMode: 'terminal',
    label: 'Claude 风格',
    // W2-15（F3-B）：delta（相对 THEME_DEFAULTS）——应用时 { ...THEME_DEFAULTS, ...delta } 干净全量换装
    theme: {
      accent: "#D77757",
      assistantDot: true,
      bgBlur: 0,
      ccBg: "#000000",
      ccHeight: 76,
      ccHidden: ["cc-send-button"],
      ccScale: {"tokens":90,"model":90,"mode":90},
      chatBg: "#000000",
      chatCodeBg: "transparent",
      chatCodeColor: "#FFC107",
      chatFontSize: 15,
      chatLineHeight: 1.3,
      chatTextColor: "#FFFFFF",
      cliLineColor: "#888888",
      cliLinePadding: 3,
      cliLineWidth: 2,
      cliPromptColor: "#999999",
      cliTextColor: "#FFFFFF",
      diffAdded: "#38A660",
      diffAddedWord: "#38A660",
      diffRemoved: "#B3596B",
      diffRemovedWord: "#B3596B",
      footerLayout: "peri",
      globalBgColor: "#000000",
      globalFont: "system",
      globalFontSize: 15,
      titlebarBg: "#000000",
      titlebarTextColor: "#FFFFFF",
      inputBg: "transparent",
      inputFocusBorder: "#505050",
      inputFontSize: 15,
      inputPlaceholder: "#999999",
      inputTextColor: "#FFFFFF",
      messageLayout: "claude",
      permissionSwitchMode: "cycle",
      modelSwitchMode: "cycle",
      msgLineHeight: 1.3,
      msgTextColor: "#FFFFFF",
      pillText: "rgba(205,214,244,0.6)",
      prismOnColor: "#4ade80",
      rightBg: "#000000",
      sendVariant: "minimal",
      sidebarBg: "#000000",
      sidebarGroupSize: 12,
      sidebarNameSize: 14,
      sidebarTextColor: "#999999",
      spinnerColor: "#D77757",
      spinnerFramePreset: "cc",
      spinnerVerbSet: "cc",
      synCoReference: "#8a9199",
      synComment: "#8a9199",
      synEntity: "#d7ba7d",
      synKeyword: "#e5a75b",
      synLiteral: "#e0964e",
      synMarkupHeading: "#61afef",
      synProperty: "#c9d1d9",
      synRegex: "#e0964e",
      synString: "#d4c05a",
      synVariable: "#c9d1d9",
      toolConnectorColor: "#505050",
      transparency: 1,
      uiScheme: "dark",
      userColor: "#D77757",
      userTagBg: "#373737",
      userTagText: "#FFFFFF",
    },
  },
  {
    name: 'glass',
    interfaceMode: 'gui',
    label: 'Glass Light',
    // W2-15（F3-B）：delta（相对 THEME_DEFAULTS）——应用时 { ...THEME_DEFAULTS, ...delta } 干净全量换装
    theme: {
      accent: "#6366f1",
      bgBlur: 24,
      ccBg: "rgba(255,255,255,0.20)",
      ccHeight: 96,
      ccHidden: ["cc-send-button"],
      ccScale: {"tokens":100,"model":100,"mode":100},
      ccVariant: "pill",
      chatBg: "rgba(255,255,255,0.28)",
      chatCodeBg: "rgba(124,58,237,0.06)",
      chatCodeColor: "#7c3aed",
      chatFont: "system",
      chatFontSize: 15,
      chatLineHeight: 1.65,
      chatTextColor: "rgba(0,0,0,0.82)",
      cliLineColor: "#9a9a9a",
      cliLinePadding: 3,
      cliLineWidth: 2,
      cliPromptColor: "#6b7280",
      cliTextColor: "rgba(0,0,0,0.80)",
      diffAdded: "#22c55e",
      diffAddedWord: "#16a34a",
      diffRemoved: "#f43f5e",
      diffRemovedWord: "#e11d48",
      globalBgColor: "#f0f0f5",
      globalFontSize: 17,
      titlebarBg: "rgba(245,245,250,0.72)",
      titlebarTextColor: "rgba(0,0,0,0.78)",
      inputBg: "rgba(0,0,0,0.03)",
      inputFocusBorder: "rgba(99,102,241,0.35)",
      inputFontSize: 15,
      inputMinHeight: 52,
      inputPlaceholder: "rgba(0,0,0,0.22)",
      inputTextColor: "rgba(0,0,0,0.80)",
      modeAutoColor: "#f59e0b",
      modeEditColor: "#6366f1",
      modelSwitchMode: "cycle",
      msgFont: "system",
      msgLineHeight: 1.75,
      pillText: "rgba(0,0,0,0.50)",
      prismOnColor: "#22c55e",
      rightBg: "rgba(245,245,250,0.55)",
      rightWidth: 250,
      sidebarBg: "rgba(245,245,250,0.55)",
      sidebarGroupSize: 12,
      sidebarNameSize: 14,
      sidebarTextColor: "rgba(0,0,0,0.75)",
      spinnerColor: "#f59e0b",
      spinnerFramePreset: "clock",
      spinnerStalledColor: "#ef4444",
      synComment: "rgba(0,0,0,0.45)",
      synEntity: "#0f766e",
      synFunction: "#1d4ed8",
      synKeyword: "#7c3aed",
      synLiteral: "#b45309",
      synMarkupHeading: "#7c3aed",
      synProperty: "rgba(0,0,0,0.82)",
      synRegex: "#b45309",
      synString: "#15803d",
      synSupport: "#1d4ed8",
      synVariable: "rgba(0,0,0,0.82)",
      toolConnectorMode: "follow",
      toolErr: "#f43f5e",
      toolIndicatorGlow: 2,
      toolOk: "#22c55e",
      toolRun: "#6366f1",
      transparency: 0.9,
      userColor: "#6366f1",
      userTagBg: "rgba(99,102,241,0.08)",
      userTagText: "#6366f1",
    },
  },
  {
    name: 'nord',
    interfaceMode: 'terminal',
    label: 'Nord Frost',
    // W2-15（F3-B）：delta（相对 THEME_DEFAULTS）——应用时 { ...THEME_DEFAULTS, ...delta } 干净全量换装
    theme: {
      accent: "#88c0d0",
      bgBlur: 12,
      ccBg: "#252838",
      ccHeight: 96,
      ccHidden: ["cc-send-button"],
      ccScale: {"tokens":95,"model":95,"mode":95},
      chatBg: "#1e2130",
      chatCodeBg: "rgba(136,192,208,0.06)",
      chatCodeColor: "#ebcb8b",
      chatFontSize: 15,
      chatLineHeight: 1.7,
      chatTextColor: "#e5e9f0",
      cliLineColor: "#7f8ea3",
      cliLinePadding: 3,
      cliLineWidth: 2,
      cliPromptColor: "#9aa7bd",
      cliTextColor: "#e5e9f0",
      diffAdded: "#a3be8c",
      diffAddedWord: "#a3be8c",
      diffRemoved: "#bf616a",
      diffRemovedWord: "#bf616a",
      globalBgColor: "#1e2130",
      globalFont: "system",
      globalFontSize: 15,
      titlebarBg: "#252838",
      titlebarTextColor: "#e5e9f0",
      inputBg: "rgba(255,255,255,0.03)",
      inputFocusBorder: "rgba(136,192,208,0.45)",
      inputFontSize: 15,
      inputMinHeight: 52,
      inputPlaceholder: "rgba(229,233,240,0.20)",
      inputTextColor: "#e5e9f0",
      modeAutoColor: "#ebcb8b",
      modeEditColor: "#88c0d0",
      modelSwitchMode: "cycle",
      msgLineHeight: 1.7,
      pillText: "rgba(136,192,208,0.75)",
      prismOnColor: "#a3be8c",
      rightBg: "#252838",
      rightWidth: 250,
      sidebarBg: "#252838",
      sidebarGroupSize: 12,
      sidebarNameSize: 14,
      sidebarTextColor: "#c8d0e0",
      spinnerColor: "#88c0d0",
      spinnerSize: 13,
      spinnerStalledColor: "#bf616a",
      synComment: "#4c566a",
      synFunction: "#88c0d0",
      synMarkupHeading: "#81a1c1",
      synProperty: "#d8dee9",
      synString: "#a3be8c",
      synSupport: "#8fbcbb",
      synVariable: "#d8dee9",
      toolConnectorColor: "#4c566a",
      toolConnectorMode: "follow",
      toolErr: "#bf616a",
      toolIndicator: "◆",
      toolIndicatorGlow: 3,
      toolOk: "#a3be8c",
      toolRun: "#88c0d0",
      transparency: 0.96,
      uiScheme: "dark",
      userColor: "#88c0d0",
      userTagBg: "rgba(136,192,208,0.12)",
      userTagText: "#88c0d0",
    },
  },
  {
    name: 'tokyo',
    interfaceMode: 'terminal',
    label: 'Tokyo Night',
    // W2-15（F3-B）：delta（相对 THEME_DEFAULTS）——应用时 { ...THEME_DEFAULTS, ...delta } 干净全量换装
    theme: {
      accent: "#7aa2f7",
      bgBlur: 0,
      ccBg: "#1a1b26",
      ccHeight: 96,
      ccHidden: ["cc-send-button"],
      ccScale: {"tokens":95,"model":95,"mode":95},
      chatBg: "#1a1b26",
      chatCodeBg: "rgba(122,162,247,0.06)",
      chatCodeColor: "#e0af68",
      chatFontSize: 15,
      chatLineHeight: 1.6,
      chatTextColor: "#c0caf5",
      cliLineColor: "#565f89",
      cliLinePadding: 3,
      cliLineWidth: 2,
      cliPromptColor: "#7f89b0",
      cliTextColor: "#c0caf5",
      diffAdded: "#9ece6a",
      diffAddedWord: "#73daca",
      diffRemoved: "#f7768e",
      diffRemovedWord: "#f7768e",
      globalBgColor: "#1a1b26",
      globalFont: "system",
      globalFontSize: 15,
      titlebarBg: "#16161e",
      titlebarTextColor: "#c0caf5",
      inputBg: "transparent",
      inputFocusBorder: "#7aa2f7",
      inputFontSize: 15,
      inputPlaceholder: "#565f89",
      inputTextColor: "#c0caf5",
      modeAutoColor: "#e0af68",
      modeEditColor: "#7aa2f7",
      permissionSwitchMode: "cycle",
      modelSwitchMode: "cycle",
      msgLineHeight: 1.6,
      msgTextColor: "#c0caf5",
      pillText: "#a9b1d6",
      prismOnColor: "#9ece6a",
      rightBg: "#16161e",
      sendVariant: "minimal",
      sidebarBg: "#16161e",
      sidebarGroupSize: 12,
      sidebarNameSize: 14,
      sidebarTextColor: "#a9b1d6",
      spinnerColor: "#bb9af7",
      spinnerFramePreset: "clock",
      spinnerStalledColor: "#f7768e",
      synComment: "#565f89",
      synEntity: "#7dcfff",
      synFunction: "#2ac3de",
      synKeyword: "#bb9af7",
      synLiteral: "#ff9e64",
      synMarkupHeading: "#7aa2f7",
      synProperty: "#c0caf5",
      synRegex: "#b4f9f8",
      synString: "#9ece6a",
      synSupport: "#2ac3de",
      synVariable: "#c0caf5",
      toolConnectorColor: "#414868",
      toolErr: "#f7768e",
      toolOk: "#9ece6a",
      toolRun: "#7aa2f7",
      transparency: 1,
      uiScheme: "dark",
      userColor: "#bb9af7",
      userTagBg: "#24283b",
      userTagText: "#bb9af7",
    },
  },
  {
    name: 'solarized',
    interfaceMode: 'gui',
    label: 'Solarized Light',
    // W2-15（F3-B）：delta（相对 THEME_DEFAULTS）——应用时 { ...THEME_DEFAULTS, ...delta } 干净全量换装
    theme: {
      accent: "#268bd2",
      bgBlur: 0,
      ccBg: "#fdf6e3",
      ccHeight: 96,
      ccHidden: ["cc-send-button"],
      ccScale: {"tokens":95,"model":95,"mode":95},
      chatBg: "#fdf6e3",
      chatCodeBg: "rgba(38,139,210,.06)",
      chatCodeColor: "#b58900",
      chatFontSize: 15,
      chatLineHeight: 1.6,
      chatTextColor: "#657b83",
      cliLineColor: "#93a1a1",
      cliLinePadding: 3,
      cliLineWidth: 2,
      cliPromptColor: "#657b83",
      cliTextColor: "#657b83",
      diffAdded: "#859900",
      diffAddedWord: "#859900",
      diffRemoved: "#dc322f",
      diffRemovedWord: "#dc322f",
      globalBgColor: "#fdf6e3",
      globalFont: "system",
      globalFontSize: 15,
      titlebarBg: "#eee8d5",
      titlebarTextColor: "#586e75",
      inputBg: "transparent",
      inputFocusBorder: "#268bd2",
      inputFontSize: 15,
      inputPlaceholder: "#93a1a1",
      inputTextColor: "#657b83",
      modeAutoColor: "#b58900",
      modeEditColor: "#268bd2",
      permissionSwitchMode: "cycle",
      modelSwitchMode: "cycle",
      msgLineHeight: 1.6,
      msgTextColor: "#657b83",
      pillText: "#586e75",
      prismOnColor: "#859900",
      rightBg: "#eee8d5",
      sendVariant: "minimal",
      sidebarBg: "#eee8d5",
      sidebarGroupSize: 12,
      sidebarNameSize: 14,
      sidebarTextColor: "#586e75",
      spinnerColor: "#b58900",
      spinnerFramePreset: "wave",
      spinnerStalledColor: "#dc322f",
      synComment: "#93a1a1",
      synEntity: "#268bd2",
      synFunction: "#268bd2",
      synKeyword: "#859900",
      synLiteral: "#d33682",
      synMarkupHeading: "#268bd2",
      synProperty: "#657b83",
      synRegex: "#d33682",
      synString: "#2aa198",
      synSupport: "#6c71c4",
      synVariable: "#657b83",
      toolConnectorColor: "#93a1a1",
      toolErr: "#dc322f",
      toolOk: "#859900",
      toolRun: "#268bd2",
      transparency: 1,
      userColor: "#268bd2",
      userTagBg: "#eee8d5",
      userTagText: "#268bd2",
    },
  },
  {
    name: 'amber',
    interfaceMode: 'terminal',
    label: 'Amber CRT',
    // W2-15（F3-B）：delta（相对 THEME_DEFAULTS）——应用时 { ...THEME_DEFAULTS, ...delta } 干净全量换装
    theme: {
      accent: "#ffb000",
      bgBlur: 0,
      ccBg: "#120b00",
      ccHeight: 96,
      ccHidden: ["cc-send-button"],
      ccScale: {"tokens":95,"model":95,"mode":95},
      chatBg: "#120b00",
      chatCodeBg: "transparent",
      chatCodeColor: "#ffe0a3",
      chatFontSize: 15,
      chatLineHeight: 1.55,
      chatTextColor: "#ffcc55",
      cliLineColor: "#9b6b00",
      cliLinePadding: 3,
      cliLineWidth: 2,
      cliPromptColor: "#cc8c00",
      cliTextColor: "#ffcc55",
      diffAdded: "#ffc24b",
      diffAddedWord: "#ffe0a3",
      diffRemoved: "#ff6b35",
      diffRemovedWord: "#ff6b35",
      globalBgColor: "#120b00",
      globalFont: "system",
      globalFontSize: 15,
      titlebarBg: "#120b00",
      titlebarTextColor: "#ffcc55",
      inputBg: "transparent",
      inputFocusBorder: "#ffb000",
      inputFontSize: 15,
      inputPlaceholder: "#7a5200",
      inputTextColor: "#ffcc55",
      modeAutoColor: "#ffb000",
      modeEditColor: "#ffcc55",
      permissionSwitchMode: "cycle",
      modelSwitchMode: "cycle",
      msgLineHeight: 1.55,
      msgTextColor: "#ffcc55",
      pillText: "#cc8c00",
      prismOnColor: "#ffc24b",
      rightBg: "#120b00",
      sendVariant: "minimal",
      sidebarBg: "#120b00",
      sidebarGroupSize: 12,
      sidebarNameSize: 14,
      sidebarTextColor: "#cc8c00",
      spinnerColor: "#ffb000",
      spinnerFramePreset: "orbit",
      spinnerStalledColor: "#ff6b35",
      synComment: "#9b6b00",
      synEntity: "#ffcc55",
      synFunction: "#ffb000",
      synKeyword: "#ffb000",
      synLiteral: "#ffb000",
      synMarkupHeading: "#ffb000",
      synProperty: "#ffcc55",
      synRegex: "#ffb000",
      synString: "#ffe0a3",
      synSupport: "#ffcc55",
      synVariable: "#ffcc55",
      toolConnectorColor: "#5c3900",
      toolErr: "#ff6b35",
      toolIndicator: "■",
      toolIndicatorGlow: 3,
      toolIndicatorGlowColor: "#ffb000",
      toolOk: "#ffc24b",
      toolRun: "#ffb000",
      transparency: 1,
      uiScheme: "dark",
      userColor: "#ffb000",
      userPrefix: ">",
      userTagBg: "#2b1900",
      userTagText: "#ffcc55",
    },
  },
  {
    name: 'matrix',
    interfaceMode: 'terminal',
    label: 'Matrix 磷绿',
    // W2-15（F3-B）：delta（相对 THEME_DEFAULTS）——应用时 { ...THEME_DEFAULTS, ...delta } 干净全量换装
    theme: {
      accent: "#39ff14",
      bgBlur: 0,
      ccBg: "#050f05",
      ccHeight: 96,
      ccHidden: ["cc-send-button"],
      ccScale: {"tokens":95,"model":95,"mode":95},
      chatBg: "#050f05",
      chatCodeBg: "rgba(57,255,20,0.06)",
      chatCodeColor: "#8effa0",
      chatFontSize: 15,
      chatLineHeight: 1.55,
      chatTextColor: "#b8ffb8",
      cliLineColor: "#1a5c1a",
      cliLinePadding: 3,
      cliLineWidth: 2,
      cliPromptColor: "#39ff14",
      cliTextColor: "#b8ffb8",
      diffAdded: "#39ff14",
      diffAddedWord: "#8effa0",
      diffRemoved: "#ff3c3c",
      diffRemovedWord: "#ff7070",
      globalBgColor: "#050f05",
      globalFont: "system",
      globalFontSize: 15,
      titlebarBg: "#050f05",
      titlebarTextColor: "#39ff14",
      inputBg: "transparent",
      inputFocusBorder: "#39ff14",
      inputFontSize: 15,
      inputPlaceholder: "#1a5c1a",
      inputTextColor: "#b8ffb8",
      modeAutoColor: "#39ff14",
      modeEditColor: "#7fff00",
      permissionSwitchMode: "cycle",
      modelSwitchMode: "cycle",
      msgLineHeight: 1.55,
      msgTextColor: "#b8ffb8",
      pillText: "#39ff14",
      prismOnColor: "#39ff14",
      rightBg: "#050f05",
      sendVariant: "minimal",
      sidebarBg: "#050f05",
      sidebarGroupSize: 12,
      sidebarNameSize: 14,
      sidebarTextColor: "#39ff14",
      spinnerColor: "#39ff14",
      spinnerFramePreset: "scan",
      spinnerStalledColor: "#ff3c3c",
      synComment: "#2d5a2d",
      synEntity: "#39ff14",
      synFunction: "#7fff00",
      synKeyword: "#39ff14",
      synLiteral: "#ffd700",
      synMarkupHeading: "#7fff00",
      synProperty: "#b8ffb8",
      synRegex: "#ffd700",
      synString: "#8effa0",
      synSupport: "#7fff00",
      synVariable: "#b8ffb8",
      toolConnectorColor: "#1a5c1a",
      toolErr: "#ff3c3c",
      toolIndicator: "»",
      toolIndicatorGlow: 3,
      toolIndicatorGlowColor: "#39ff14",
      toolOk: "#39ff14",
      toolRun: "#7fff00",
      transparency: 1,
      uiScheme: "dark",
      userColor: "#7fff00",
      userTagBg: "#0a1a0a",
      userTagText: "#7fff00",
    },
  },
  {
    name: 'agent-command',
    interfaceMode: 'gui',
    label: 'Agent 指挥台',
    presentationProfileId: 'builtin.presentation.agent-command',
    theme: {
      accent: '#38bdf8',
      globalBgColor: '#08111f',
      globalFont: 'system',
      globalFontSize: 15,
      titlebarBg: '#0b1424',
      titlebarTextColor: '#dbeafe',
      sidebarBg: '#0b1424',
      sidebarTextColor: '#a8bdd6',
      sidebarNameSize: 14,
      chatBg: '#08111f',
      chatTextColor: '#dbeafe',
      chatCodeBg: 'rgba(56,189,248,0.07)',
      chatCodeColor: '#7dd3fc',
      messageLayout: 'bubble',
      msgLineHeight: 1.62,
      ccBg: '#0d192b',
      ccHeight: 96,
      inputBg: 'rgba(148,163,184,0.09)',
      inputTextColor: '#e0f2fe',
      inputPlaceholder: '#647d99',
      inputFocusBorder: 'rgba(56,189,248,0.72)',
      rightBg: '#0b1424',
      userColor: '#38bdf8',
      userTagBg: 'rgba(56,189,248,0.12)',
      userTagText: '#7dd3fc',
      spinnerColor: '#38bdf8',
      toolOk: '#4ade80',
      toolRun: '#38bdf8',
      toolErr: '#fb7185',
      toolConnectorColor: '#294764',
      diffAdded: '#4ade80',
      diffRemoved: '#fb7185',
      diffAddedWord: '#86efac',
      diffRemovedWord: '#fda4af',
      uiScheme: 'dark',
      transparency: 1,
    },
  },
  {
    name: 'agent-map',
    interfaceMode: 'gui',
    label: 'Agent 关系图',
    presentationProfileId: 'builtin.presentation.agent-map',
    theme: {
      accent: '#a78bfa',
      globalBgColor: '#11101d',
      globalFont: 'system',
      globalFontSize: 15,
      titlebarBg: '#171526',
      titlebarTextColor: '#ede9fe',
      sidebarBg: '#171526',
      sidebarTextColor: '#c4b5d9',
      sidebarNameSize: 14,
      chatBg: '#11101d',
      chatTextColor: '#ede9fe',
      chatCodeBg: 'rgba(167,139,250,0.08)',
      chatCodeColor: '#c4b5fd',
      messageLayout: 'bubble',
      msgLineHeight: 1.68,
      ccBg: '#1a172b',
      ccHeight: 96,
      inputBg: 'rgba(167,139,250,0.08)',
      inputTextColor: '#f5f3ff',
      inputPlaceholder: '#766c91',
      inputFocusBorder: 'rgba(167,139,250,0.72)',
      rightBg: '#171526',
      userColor: '#a78bfa',
      userTagBg: 'rgba(167,139,250,0.13)',
      userTagText: '#c4b5fd',
      spinnerColor: '#a78bfa',
      toolOk: '#5eead4',
      toolRun: '#a78bfa',
      toolErr: '#fb7185',
      toolConnectorColor: '#494064',
      diffAdded: '#5eead4',
      diffRemoved: '#fb7185',
      diffAddedWord: '#99f6e4',
      diffRemovedWord: '#fda4af',
      uiScheme: 'dark',
      transparency: 1,
    },
  },
  {
    name: 'focus-flow',
    interfaceMode: 'gui',
    label: '专注流程',
    presentationProfileId: 'builtin.presentation.focus-flow',
    theme: {
      accent: '#d6a85f',
      globalBgColor: '#181713',
      globalFont: 'system',
      globalFontSize: 15,
      titlebarBg: '#1d1b17',
      titlebarTextColor: '#eee8dc',
      sidebarBg: '#1d1b17',
      sidebarTextColor: '#b8afa0',
      sidebarNameSize: 14,
      chatBg: '#181713',
      chatTextColor: '#e7e0d5',
      chatCodeBg: 'rgba(214,168,95,0.06)',
      chatCodeColor: '#dfbd83',
      messageLayout: 'claude',
      msgLineHeight: 1.72,
      ccBg: '#201e19',
      ccHeight: 88,
      inputBg: 'rgba(214,168,95,0.05)',
      inputTextColor: '#eee8dc',
      inputPlaceholder: '#81796d',
      inputFocusBorder: 'rgba(214,168,95,0.55)',
      rightBg: '#1d1b17',
      userColor: '#d6a85f',
      userTagBg: 'rgba(214,168,95,0.10)',
      userTagText: '#dfbd83',
      spinnerColor: '#d6a85f',
      toolOk: '#a3b18a',
      toolRun: '#d6a85f',
      toolErr: '#cf7b73',
      toolConnectorColor: '#4b463d',
      diffAdded: '#a3b18a',
      diffRemoved: '#cf7b73',
      diffAddedWord: '#c3ceb2',
      diffRemovedWord: '#e3aaa4',
      uiScheme: 'dark',
      transparency: 1,
    },
  }
]

/** Public registry: terminal presets are projected to complete snapshots. */
export const GLOBAL_PRESETS: GlobalPreset[] = RAW_GLOBAL_PRESETS.map(completeTerminalPreset)

/**
 * 刀5（#201）：界面模式 → 预设归属桶。
 * 归属表只有 GUI / 终端 两桶（用户 2026-09-19 拍板）；`tactical-blue` 是独立插入的
 * 界面模式、与预设轴零交集 ⇒ 不在映射内（其模式下预设菜单不出现），插件贡献的
 * 未登记模式同理不出现。
 */
export const INTERFACE_MODE_PRESET_BUCKET: Readonly<Record<string, PresetInterfaceMode>> = Object.freeze({
  'modern-gui': 'gui',
  'terminal-like': 'terminal',
})

function requireGlobalPreset(name: PresetName): GlobalPreset {
  const preset = GLOBAL_PRESETS.find(item => item.name === name)
  if (!preset) throw new Error(`内置预设缺失：${name}`)
  return preset
}

/**
 * 刀7（#214）：两条「默认预设」——GUI / 终端各一条。
 *
 * **同定位、不同按键**（用户 2026-09-20 拍板）：它们与普通预设是同一个 `GlobalPreset`
 * 形状、走同一条应用路径，唯一区别是**触达方式**——唯一入口是「重置主题」。
 *
 * **为什么是独立表而不是往 `GLOBAL_PRESETS` 里加标记**：「不显示」若靠过滤分支实现，
 * 就得同时改「列表」（`presetsForInterfaceMode`）与「区域池」（`zonePresetPool` 的派生表），
 * 漏一处它们就漏进候选菜单。独立表让两处排除变成**结构性保证**（谁都不读它），
 * 且 `GLOBAL_PRESETS` 仍是 10 套——`docs/说明书` 里「当前 10 套内置预设」不失真。
 *
 * 外观来源（用户拍板）：
 * - GUI：取 `glass` 的四区切面（**引用**同一份 theme 数据）；
 * - 终端：**复制** `glass`（最早那款浅色；深色的 nord/tokyo/amber/matrix/claude 用户已否决）
 *   + 终端契约字段（写法对齐 `completion.ts` 的 `TERMINAL_VISUAL_COMPLETION`：
 *   `msgStyle` / `messageLayout` / `inputMode` / `inputVariant` / `ccVariant`）。
 *   其中 `inputVariant` 与 `inputMode` 必须同写——`inputMode==='cli' ⟺ inputVariant==='cli'`
 *   是本仓既有的联动不变量（`presetReducer.resolveInputMode`）。
 */
const GLASS_THEME: Partial<ThemeSettings> = requireGlobalPreset('glass').theme

/** 终端默认 = `glass` 的副本 + 终端契约字段（`inputVariant` 与 `inputMode` 必须同写）。 */
const TERMINAL_DEFAULT_THEME: Partial<ThemeSettings> = {
  ...structuredClone(GLASS_THEME),
  msgStyle: 'terminal',
  messageLayout: 'classic',
  inputMode: 'cli',
  inputVariant: 'cli',
  ccVariant: 'terminal',
}

export const DEFAULT_PRESETS: Readonly<Record<PresetInterfaceMode, GlobalPreset>> = Object.freeze({
  gui: Object.freeze({
    name: 'gui-default',
    label: 'GUI-默认预设',
    interfaceMode: 'gui',
    theme: GLASS_THEME,
  }),
  terminal: Object.freeze({
    name: 'terminal-default',
    label: '终端-默认预设',
    interfaceMode: 'terminal',
    theme: TERMINAL_DEFAULT_THEME,
  }),
})

/** 当前界面模式对应的默认预设（**未登记模式 ⇒ undefined** ⇒ 调用方回落 `DEFAULTS`）。 */
export function defaultPresetForInterfaceMode(interfaceMode: string): GlobalPreset | undefined {
  const bucket = INTERFACE_MODE_PRESET_BUCKET[interfaceMode]
  return bucket ? DEFAULT_PRESETS[bucket] : undefined
}

/** 当前界面模式下可出现在预设菜单第二级的预设（桶未登记 ⇒ 空数组 = 菜单不出现）。 */
export function presetsForInterfaceMode(interfaceMode: string): GlobalPreset[] {
  const bucket = INTERFACE_MODE_PRESET_BUCKET[interfaceMode]
  return bucket ? GLOBAL_PRESETS.filter(preset => preset.interfaceMode === bucket) : []
}

/**
 * #116 子项 7：「全局预设」行的兜底 chip 判据（从 Settings.tsx 抽出以便单测）。
 *
 * `deriveGlobalStatus` 可能返回三种值：内置预设的 name、`'custom'` 哨兵（任一 zone
 * 被手动改过）、自定义预设的 id。原先的兜底判据只排除内置 name，于是后两种都会把
 * **原文**渲染成一个 chip —— 用户看到 `custom-1788421103162` 这类内部标识，且与
 * `.set-custom-presets` 里的具名 chip 同时点亮。
 *
 * 现在的口径：
 * - 内置预设 name → 无兜底（上面那排 chip 自己就是选中态）
 * - 自定义预设 id → 无兜底（交给具名列表渲染，避免重复点亮）
 * - `'custom'` 哨兵 → 显示为「自定义」
 * - 其余无法识别的值 → 显示为「未知预设」，原值只在 title 里留作排查线索
 */
export function fallbackPresetChip(
  globalStatus: string,
  customPresetIds: readonly string[],
): { label: string; title: string } | null {
  if (!globalStatus) return null
  if (GLOBAL_PRESETS.some(preset => preset.name === globalStatus)) return null
  if (customPresetIds.includes(globalStatus)) return null
  if (globalStatus === 'custom') return { label: '自定义', title: '当前外观已偏离预设基准' }
  return { label: '未知预设', title: `未识别的预设标识：${globalStatus}` }
}
