import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

const root = new URL('../src/components/', import.meta.url)
const right = await readFile(new URL('RightPanel.tsx', root), 'utf8')
const workspace = await readFile(new URL('right-panel/WorkspacePanel.tsx', root), 'utf8')
const types = await readFile(new URL('right-panel/rightPanelTypes.ts', root), 'utf8')
const tabs = await readFile(new URL('right-panel/RightPanelTabs.tsx', root), 'utf8')

assert.match(right, /import WorkspacePanel from ['"]\.\/right-panel\/WorkspacePanel['"]/, 'RightPanel must import WorkspacePanel')
assert.match(right, /import \{ useStore \} from ['"]\.\.\/store['"]/, 'RightPanel must resolve source from the store')
assert.match(right, /resolveSessionSource\(sessionId, sessions\)/, 'RightPanel must resolve Session.id to Session.source')
assert.match(right, /createLogsViewState\(sessionSource \? \{ sessionId: sessionId as string, source: sessionSource \} : null\)/, 'logs scope must use resolved backend source')
assert.doesNotMatch(right, /source: sessionId/, 'local Session.id must not be used as backend source')
assert.match(right, /useState<WorkspaceViewState>/, 'workspace state must be component-local state')
assert.match(right, /createWorkspaceViewState\(sessionSource\)/, 'workspace state must use resolved source scope')
assert.match(right, /<WorkspacePanel[\s\S]*state=\{workspaceState\}/, 'workspace tab must render WorkspacePanel with state')
assert.match(right, /transitionWorkspaceView\(state, \{ type: ['"]select['"], path \}\)/, 'selection must remain local')
assert.match(right, /\}, \[sessionSource\]\)/, 'workspace state must reset when source changes')
assert.match(right, /tab === ['"]logs['"][\s\S]*<LogsPanel state=\{logsState\}/, 'LogsPanel must replace the old static logs placeholder')
assert.match(right, /tab === ['"]reserved-1['"][\s\S]*ReservedTab/, 'reserved-1 branch must remain')
assert.match(right, /tab === ['"]reserved-2['"][\s\S]*ReservedTab/, 'reserved-2 branch must remain')
assert.match(tabs, /id: ['"]workspace['"]/)
assert.match(tabs, /id: ['"]logs['"]/)
assert.match(tabs, /id: ['"]reserved-1['"]/)
assert.match(tabs, /id: ['"]reserved-2['"]/)
assert.match(workspace, /export default function WorkspacePanel/)
assert.match(types, /export function createWorkspaceViewState\(sessionId: string \| null\)/)
assert.match(right, /invoke<unknown>\('list_workspace_entries', \{ source: sessionSource \}\)/, 'Workspace must call the confirmed source-scoped command')
assert.match(right, /invoke<unknown>\('read_workspace_text', \{ source: sessionSource, relativePath: path \}\)/, 'RightPanel must call read_workspace_text with source and relativePath')
assert.match(right, /onExpand=\{expandWorkspace\}/, 'WorkspacePanel must receive expand handler')
assert.match(right, /onRead=\{readWorkspaceText\}/, 'WorkspacePanel must receive read handler')
assert.match(right, /workspace-text-preview/, 'RightPanel must render bounded text preview')

console.log('RightPanel WorkspacePanel wiring: PASS')
