import { strict as assert } from 'node:assert'
import { readFileSync } from 'node:fs'

const app = readFileSync(new URL('../src/App.tsx', import.meta.url), 'utf8')
const css = readFileSync(new URL('../src/components/ControlCenter.css', import.meta.url), 'utf8')
const controlCenter = readFileSync(new URL('../src/components/ControlCenter.tsx', import.meta.url), 'utf8')
const inputCss = readFileSync(new URL('../src/components/chat/InputBar.css', import.meta.url), 'utf8')
const inputBar = readFileSync(new URL('../src/components/chat/InputBar.tsx', import.meta.url), 'utf8')
const store = readFileSync(new URL('../src/store.ts', import.meta.url), 'utf8')
const presets = readFileSync(new URL('../src/presets.ts', import.meta.url), 'utf8')

assert.equal(app.includes('ccStatusFontSize'), true)
assert.equal(app.includes("'--cc-status-font-size'"), true)
assert.equal(css.includes('font-size:max(14px, var(--cc-status-font-size, 14px))'), true)
assert.equal(css.includes('min-height:64px'), true)
assert.equal(store.includes('ccStatusFontSize: 14'), true)
assert.equal(store.includes('ccStatusFontSize: number'), true)
assert.equal(inputCss.includes('padding:var(--cli-line-padding,6px) 0'), true)
assert.equal(inputCss.includes('padding:0 8px 0 4px'), true)
assert.equal(inputCss.includes('var(--cli-prompt-color,var(--cli-text-color,#999))'), true)
assert.equal(inputCss.includes('var(--cli-content-offset-y,0px)'), true)
assert.equal(controlCenter.includes('className="cc-command-hint"'), true)
assert.equal(controlCenter.includes("cliHintMode !== 'hidden'"), true)
assert.equal(controlCenter.includes("cliHintMode === 'full'"), true)
assert.equal(controlCenter.includes('<span className="cc-command-hint-line"><span>/</span>: 命令 <i>|</i> Shift+Enter: 换行</span>'), true)
assert.equal(controlCenter.includes('<span className="cc-command-hint-line">Shift+Tab: 模式</span>'), true)
assert.equal(inputBar.includes("e.key === 'Tab' && e.shiftKey && sessionSource"), true)
assert.equal(inputBar.includes('nextSessionMode(currentMode)'), true)
assert.equal(css.includes('.cc-command-hint'), true)
assert.equal(css.includes('flex-direction:column'), true)
assert.equal(css.includes('.cc-command-hint-line'), true)
assert.equal(css.includes('margin-left:auto'), true)
assert.equal(store.includes('cliPromptColor: string'), true)
assert.equal(store.includes("cliHintMode: 'hidden' | 'compact' | 'full'"), true)
assert.equal(presets.includes('ccHeight: 76'), true)
assert.equal(presets.includes('inputFontSize: 15'), true)
assert.equal(presets.includes("cliPromptColor: '#999999'"), true)

console.log('controlCenterResponsive 回归测试通过')
