import { strict as assert } from 'node:assert'
import { readFileSync } from 'node:fs'

const root = new URL('../', import.meta.url)
const app = readFileSync(new URL('src/App.tsx', root), 'utf8')
const store = readFileSync(new URL('src/store.ts', root), 'utf8')
const presets = readFileSync(new URL('src/presets.ts', root), 'utf8')
const customPresets = readFileSync(new URL('src/customPresets.ts', root), 'utf8')
const settings = readFileSync(new URL('src/components/Settings.tsx', root), 'utf8')
const controlCenter = readFileSync(new URL('src/components/ControlCenter.tsx', root), 'utf8')
const controlCenterCss = readFileSync(new URL('src/components/ControlCenter.css', root), 'utf8')
const ccHeightState = readFileSync(new URL('src/ccHeightState.ts', root), 'utf8')
const inputBar = readFileSync(new URL('src/components/chat/InputBar.tsx', root), 'utf8')
const inputBarCss = readFileSync(new URL('src/components/chat/InputBar.css', root), 'utf8')

assert.match(store, /messageLayout:\s*'classic' \| 'claude' \| 'bubble'/)
assert.match(store, /footerLayout:\s*'free' \| 'peri'/)
assert.match(store, /cliOverflowMode:\s*'fixed-scroll' \| 'grow' \| 'overlay'/)
assert.match(store, /messageLayout:\s*'classic', footerLayout:\s*'free', cliOverflowMode:\s*'fixed-scroll'/)
assert.match(store, /state\.messageLayout = state\.messageLayout === 'claude' \|\| state\.messageLayout === 'bubble' \? state\.messageLayout : 'classic'/)
assert.match(store, /state\.footerLayout = state\.footerLayout === 'peri' \? 'peri' : 'free'/)
assert.match(store, /state\.cliOverflowMode = state\.cliOverflowMode === 'grow' \|\| state\.cliOverflowMode === 'overlay' \? state\.cliOverflowMode : 'fixed-scroll'/)

assert.match(presets, /'msgStyle', 'msgFont', 'msgTextColor', 'msgLineHeight', 'messageLayout'/)
assert.match(presets, /'cliHintMode', 'footerLayout', 'cliOverflowMode'/)
assert.match(presets, /messageLayout: 'claude', footerLayout: 'peri', cliOverflowMode: 'fixed-scroll'/)
assert.ok((presets.match(/messageLayout/g) || []).length >= 6, '每个内建预设都应声明 messageLayout')

assert.match(customPresets, /'msgStyle', 'msgFont', 'msgTextColor', 'msgLineHeight', 'messageLayout'/)
assert.match(customPresets, /'ccCliCustomized', 'ccScale', 'footerLayout', 'cliOverflowMode'/)

assert.match(app, /data-message-layout=\{s\.messageLayout \|\| 'classic'\}/)
assert.match(app, /data-footer-layout=\{s\.footerLayout \|\| 'free'\}/)
assert.match(app, /data-cli-overflow-mode=\{s\.cliOverflowMode \|\| 'fixed-scroll'\}/)
assert.match(settings, /options=\{\['classic','claude','bubble'\]\}/)
assert.match(settings, /options=\{\['free','peri'\]\}/)
assert.match(settings, /options=\{\['fixed-scroll','grow','overlay'\]\}/)
assert.match(controlCenter, /footerLayout === 'peri'/)
assert.match(controlCenter, /className="cc-footer cc-footer-peri"/)
assert.match(controlCenter, /className="cc-footer-status-row"/)
assert.match(controlCenterCss, /\.cc-footer-peri \{ display:flex; flex-direction:column;/)
assert.match(controlCenterCss, /\.cc-footer-status-row \{ display:flex; align-items:center;/)
assert.match(ccHeightState, /export function resolveCcMinHeight/)
assert.match(ccHeightState, /export function resolveVisibleStatusWidgetCount/)
assert.match(ccHeightState, /if \(cliOverflowMode === 'grow'\) return BASE_MIN_HEIGHT/)
assert.match(store, /clampCcHeight\(height, \{/)
assert.match(store, /state\.ccHeight = clampCcHeight/)
assert.match(controlCenterCss, /min-height:var\(--cc-min-height,64px\)/)
assert.match(settings, /min=\{ccMinHeight\}/)
assert.match(inputBar, /resolveCliTextareaLayout\(textarea\.scrollHeight, cliOverflowMode\)/)
assert.match(inputBar, /cli-overflow-\$\{cliOverflowMode\}/)
assert.match(inputBarCss, /\.input-bar\.cli-mode\.cli-overflow-fixed-scroll/)
assert.match(inputBarCss, /\.input-bar\.cli-mode\.cli-overflow-overlay \.input-textarea\[data-expanded="true"\]/)
assert.match(controlCenterCss, /data-cli-overflow-mode="grow"/)

console.log('layoutModeContract 回归测试通过')
