/**
 * presets.ts — 全局/局部预设定义 + 区域字段映射
 *
 * 分区（zone）：
 *   global  — 全局玻璃效果、字体、用户信息
 *   sidebar — 左侧栏
 *   chat    — 聊天区 + 工具调用
 *   cc      — 中控区（输入栏、状态栏、EKG）
 *   right   — 右侧栏
 */

import type { ThemeSettings } from './store'
import { ZONE_FIELDS } from './themeFieldDefs.ts'

// ── 区域字段映射 ────────────────────────────────────────────────
// 单一真值表在 themeFields.ts；本文件仅 re-export，保证旧导入路径不变。

export { ZONE_FIELDS }

// ── 预设定义 ─────────────────────────────────────────────────────

export type PresetName = 'claude' | 'glass' | 'nord' | 'tokyo' | 'solarized' | 'amber'

export interface GlobalPreset {
  name: PresetName
  label: string
  theme: Partial<ThemeSettings>
}

export const GLOBAL_PRESETS: GlobalPreset[] = [
  {
    name: 'claude',
    label: 'Claude 风格',
    // W2-15（F3-B）：delta（相对 THEME_DEFAULTS）——应用时 { ...THEME_DEFAULTS, ...delta } 干净全量换装
    theme: {
      accent: "#D77757",
      assistantDot: true,
      attachVariant: "minimal",
      barTrackColor: "#353117",
      bgBlur: 0,
      ccBg: "#000000",
      ccBgHeight: 76,
      ccHeight: 76,
      ccHidden: ["send","attach"],
      ccScale: {"ekg":90,"pct":90,"tokens":90,"model":90,"mode":90},
      ccStyle: "numeric",
      chatBg: "#000000",
      chatCodeBg: "transparent",
      chatCodeColor: "#FFC107",
      chatFontSize: 15,
      chatLineHeight: 1.3,
      chatTextColor: "#FFFFFF",
      cliLineColor: "#888888",
      cliLinePadding: 3,
      cliLineWidth: 2,
      cliPromptColor: "#999999",
      cliTextColor: "#FFFFFF",
      diffAdded: "#38A660",
      diffAddedWord: "#38A660",
      diffRemoved: "#B3596B",
      diffRemovedWord: "#B3596B",
      ekgGreen: "#4ade80",
      ekgRed: "#f87171",
      ekgWidth: 140,
      ekgYellow: "#fbbf24",
      footerLayout: "peri",
      globalBgColor: "#000000",
      globalFont: "system",
      globalFontSize: 15,
      titlebarBg: "#000000",
      titlebarTextColor: "#FFFFFF",
      inputBg: "transparent",
      inputFocusBorder: "#505050",
      inputFontSize: 17,
      inputPlaceholder: "#999999",
      inputSendBg: "transparent",
      inputTextColor: "#FFFFFF",
      messageLayout: "claude",
      modeVariant: "minimal",
      modelVariant: "minimal",
      msgLineHeight: 1.3,
      msgTextColor: "#FFFFFF",
      pillBg: "rgba(255,255,255,0.05)",
      pillText: "rgba(205,214,244,0.6)",
      prismOnColor: "#4ade80",
      rightBg: "#000000",
      sendVariant: "minimal",
      sidebarBg: "#000000",
      sidebarGroupSize: 11,
      sidebarNameSize: 13,
      sidebarTextColor: "#999999",
      spinnerColor: "#D77757",
      spinnerFramePreset: "cc",
      spinnerVerbSet: "cc",
      synCoReference: "#8a9199",
      synComment: "#8a9199",
      synEntity: "#d7ba7d",
      synKeyword: "#e5a75b",
      synLiteral: "#e0964e",
      synMarkupHeading: "#61afef",
      synProperty: "#c9d1d9",
      synRegex: "#e0964e",
      synString: "#d4c05a",
      synVariable: "#c9d1d9",
      toolConnectorColor: "#505050",
      transparency: 1,
      uiScheme: "dark",
      userColor: "#D77757",
      userTagBg: "#373737",
      userTagText: "#FFFFFF",
    },
  },
  {
    name: 'glass',
    label: 'Glass Light',
    // W2-15（F3-B）：delta（相对 THEME_DEFAULTS）——应用时 { ...THEME_DEFAULTS, ...delta } 干净全量换装
    theme: {
      accent: "#6366f1",
      barFillColor: "#22c55e",
      barTrackColor: "rgba(0,0,0,0.06)",
      bgBlur: 24,
      ccBg: "rgba(255,255,255,0.20)",
      ccBgHeight: 96,
      ccHeight: 96,
      ccHidden: ["send","attach"],
      ccScale: {"ekg":105,"pct":105,"tokens":100,"model":100,"mode":100},
      ccStyle: "bar",
      ccVariant: "pill",
      chatBg: "rgba(255,255,255,0.28)",
      chatCodeBg: "rgba(124,58,237,0.06)",
      chatCodeColor: "#7c3aed",
      chatFont: "system",
      chatFontSize: 15,
      chatLineHeight: 1.65,
      chatTextColor: "rgba(0,0,0,0.82)",
      cliLineColor: "#9a9a9a",
      cliLinePadding: 3,
      cliLineWidth: 2,
      cliPromptColor: "#6b7280",
      cliTextColor: "rgba(0,0,0,0.80)",
      diffAdded: "#22c55e",
      diffAddedWord: "#16a34a",
      diffRemoved: "#f43f5e",
      diffRemovedWord: "#e11d48",
      ekgGreen: "#22c55e",
      ekgRed: "#ef4444",
      ekgWidth: 130,
      ekgYellow: "#f59e0b",
      globalBgColor: "#f0f0f5",
      globalFontSize: 17,
      titlebarBg: "rgba(245,245,250,0.72)",
      titlebarTextColor: "rgba(0,0,0,0.78)",
      inputBg: "rgba(0,0,0,0.03)",
      inputFocusBorder: "rgba(99,102,241,0.35)",
      inputFontSize: 17,
      inputMinHeight: 52,
      inputPlaceholder: "rgba(0,0,0,0.22)",
      inputSendBg: "rgba(99,102,241,0.12)",
      inputTextColor: "rgba(0,0,0,0.80)",
      modeAutoColor: "#f59e0b",
      modeEditColor: "#6366f1",
      modelVariant: "badge",
      msgFont: "system",
      msgLineHeight: 1.75,
      pillBg: "rgba(0,0,0,0.04)",
      pillText: "rgba(0,0,0,0.50)",
      prismOnColor: "#22c55e",
      rightBg: "rgba(245,245,250,0.55)",
      rightWidth: 250,
      sidebarBg: "rgba(245,245,250,0.55)",
      sidebarGroupSize: 11,
      sidebarNameSize: 13,
      sidebarTextColor: "rgba(0,0,0,0.75)",
      spinnerColor: "#f59e0b",
      spinnerFramePreset: "clock",
      spinnerStalledColor: "#ef4444",
      synComment: "rgba(0,0,0,0.45)",
      synEntity: "#0f766e",
      synFunction: "#1d4ed8",
      synKeyword: "#7c3aed",
      synLiteral: "#b45309",
      synMarkupHeading: "#7c3aed",
      synProperty: "rgba(0,0,0,0.82)",
      synRegex: "#b45309",
      synString: "#15803d",
      synSupport: "#1d4ed8",
      synVariable: "rgba(0,0,0,0.82)",
      toolConnectorMode: "follow",
      toolErr: "#f43f5e",
      toolIndicatorGlow: 2,
      toolOk: "#22c55e",
      toolRun: "#6366f1",
      transparency: 0.9,
      userColor: "#6366f1",
      userTagBg: "rgba(99,102,241,0.08)",
      userTagText: "#6366f1",
    },
  },
  {
    name: 'nord',
    label: 'Nord Frost',
    // W2-15（F3-B）：delta（相对 THEME_DEFAULTS）——应用时 { ...THEME_DEFAULTS, ...delta } 干净全量换装
    theme: {
      accent: "#88c0d0",
      barFillColor: "#88c0d0",
      barTrackColor: "rgba(136,192,208,0.10)",
      bgBlur: 12,
      ccBg: "#252838",
      ccBgHeight: 96,
      ccHeight: 96,
      ccHidden: ["send","attach"],
      ccScale: {"ekg":100,"pct":95,"tokens":95,"model":95,"mode":95},
      ccStyle: "bar",
      chatBg: "#1e2130",
      chatCodeBg: "rgba(136,192,208,0.06)",
      chatCodeColor: "#ebcb8b",
      chatFontSize: 15,
      chatLineHeight: 1.7,
      chatTextColor: "#e5e9f0",
      cliLineColor: "#7f8ea3",
      cliLinePadding: 3,
      cliLineWidth: 2,
      cliPromptColor: "#9aa7bd",
      cliTextColor: "#e5e9f0",
      diffAdded: "#a3be8c",
      diffAddedWord: "#a3be8c",
      diffRemoved: "#bf616a",
      diffRemovedWord: "#bf616a",
      ekgGreen: "#a3be8c",
      ekgRed: "#bf616a",
      ekgWidth: 140,
      ekgYellow: "#ebcb8b",
      globalBgColor: "#1e2130",
      globalFont: "system",
      globalFontSize: 15,
      titlebarBg: "#252838",
      titlebarTextColor: "#e5e9f0",
      inputBg: "rgba(255,255,255,0.03)",
      inputFocusBorder: "rgba(136,192,208,0.45)",
      inputFontSize: 17,
      inputMinHeight: 52,
      inputPlaceholder: "rgba(229,233,240,0.20)",
      inputSendBg: "rgba(136,192,208,0.15)",
      inputTextColor: "#e5e9f0",
      modeAutoColor: "#ebcb8b",
      modeEditColor: "#88c0d0",
      modelVariant: "minimal",
      msgLineHeight: 1.7,
      pillBg: "rgba(136,192,208,0.08)",
      pillText: "rgba(136,192,208,0.75)",
      prismOnColor: "#a3be8c",
      rightBg: "#252838",
      rightWidth: 250,
      sidebarBg: "#252838",
      sidebarGroupSize: 11,
      sidebarNameSize: 13,
      sidebarTextColor: "#c8d0e0",
      spinnerColor: "#88c0d0",
      spinnerSize: 13,
      spinnerStalledColor: "#bf616a",
      synComment: "#4c566a",
      synFunction: "#88c0d0",
      synMarkupHeading: "#81a1c1",
      synProperty: "#d8dee9",
      synString: "#a3be8c",
      synSupport: "#8fbcbb",
      synVariable: "#d8dee9",
      toolConnectorColor: "#4c566a",
      toolConnectorMode: "follow",
      toolErr: "#bf616a",
      toolIndicator: "◆",
      toolIndicatorGlow: 3,
      toolOk: "#a3be8c",
      toolRun: "#88c0d0",
      transparency: 0.96,
      uiScheme: "dark",
      userColor: "#88c0d0",
      userTagBg: "rgba(136,192,208,0.12)",
      userTagText: "#88c0d0",
    },
  },
  {
    name: 'tokyo',
    label: 'Tokyo Night',
    // W2-15（F3-B）：delta（相对 THEME_DEFAULTS）——应用时 { ...THEME_DEFAULTS, ...delta } 干净全量换装
    theme: {
      accent: "#7aa2f7",
      attachVariant: "minimal",
      barFillColor: "#7aa2f7",
      barHeight: 8,
      barTrackColor: "#24283b",
      bgBlur: 0,
      ccBg: "#1a1b26",
      ccBgHeight: 96,
      ccHeight: 96,
      ccHidden: ["send","attach"],
      ccScale: {"pct":95,"tokens":95,"model":95,"mode":95},
      ccStyle: "numeric",
      chatBg: "#1a1b26",
      chatCodeBg: "rgba(122,162,247,0.06)",
      chatCodeColor: "#e0af68",
      chatFontSize: 15,
      chatLineHeight: 1.6,
      chatTextColor: "#c0caf5",
      cliLineColor: "#565f89",
      cliLinePadding: 3,
      cliLineWidth: 2,
      cliPromptColor: "#7f89b0",
      cliTextColor: "#c0caf5",
      diffAdded: "#9ece6a",
      diffAddedWord: "#73daca",
      diffRemoved: "#f7768e",
      diffRemovedWord: "#f7768e",
      ekgGreen: "#9ece6a",
      ekgRed: "#f7768e",
      ekgWidth: 140,
      ekgYellow: "#e0af68",
      globalBgColor: "#1a1b26",
      globalFont: "system",
      globalFontSize: 15,
      titlebarBg: "#16161e",
      titlebarTextColor: "#c0caf5",
      inputBg: "transparent",
      inputFocusBorder: "#7aa2f7",
      inputFontSize: 17,
      inputPlaceholder: "#565f89",
      inputSendBg: "transparent",
      inputTextColor: "#c0caf5",
      modeAutoColor: "#e0af68",
      modeEditColor: "#7aa2f7",
      modeVariant: "minimal",
      modelVariant: "minimal",
      msgLineHeight: 1.6,
      msgTextColor: "#c0caf5",
      pillBg: "#24283b",
      pillText: "#a9b1d6",
      prismOnColor: "#9ece6a",
      rightBg: "#16161e",
      sendVariant: "minimal",
      sidebarBg: "#16161e",
      sidebarGroupSize: 11,
      sidebarNameSize: 13,
      sidebarTextColor: "#a9b1d6",
      spinnerColor: "#bb9af7",
      spinnerFramePreset: "clock",
      spinnerStalledColor: "#f7768e",
      synComment: "#565f89",
      synEntity: "#7dcfff",
      synFunction: "#2ac3de",
      synKeyword: "#bb9af7",
      synLiteral: "#ff9e64",
      synMarkupHeading: "#7aa2f7",
      synProperty: "#c0caf5",
      synRegex: "#b4f9f8",
      synString: "#9ece6a",
      synSupport: "#2ac3de",
      synVariable: "#c0caf5",
      toolConnectorColor: "#414868",
      toolErr: "#f7768e",
      toolOk: "#9ece6a",
      toolRun: "#7aa2f7",
      transparency: 1,
      uiScheme: "dark",
      userColor: "#bb9af7",
      userTagBg: "#24283b",
      userTagText: "#bb9af7",
    },
  },
  {
    name: 'solarized',
    label: 'Solarized Light',
    // W2-15（F3-B）：delta（相对 THEME_DEFAULTS）——应用时 { ...THEME_DEFAULTS, ...delta } 干净全量换装
    theme: {
      accent: "#268bd2",
      attachVariant: "minimal",
      barFillColor: "#268bd2",
      barHeight: 8,
      barTrackColor: "#eee8d5",
      bgBlur: 0,
      ccBg: "#fdf6e3",
      ccBgHeight: 96,
      ccHeight: 96,
      ccHidden: ["send","attach"],
      ccScale: {"pct":95,"tokens":95,"model":95,"mode":95},
      ccStyle: "numeric",
      chatBg: "#fdf6e3",
      chatCodeBg: "rgba(38,139,210,.06)",
      chatCodeColor: "#b58900",
      chatFontSize: 15,
      chatLineHeight: 1.6,
      chatTextColor: "#657b83",
      cliLineColor: "#93a1a1",
      cliLinePadding: 3,
      cliLineWidth: 2,
      cliPromptColor: "#657b83",
      cliTextColor: "#657b83",
      diffAdded: "#859900",
      diffAddedWord: "#859900",
      diffRemoved: "#dc322f",
      diffRemovedWord: "#dc322f",
      ekgGreen: "#859900",
      ekgRed: "#dc322f",
      ekgWidth: 140,
      ekgYellow: "#b58900",
      globalBgColor: "#fdf6e3",
      globalFont: "system",
      globalFontSize: 15,
      titlebarBg: "#eee8d5",
      titlebarTextColor: "#586e75",
      inputBg: "transparent",
      inputFocusBorder: "#268bd2",
      inputFontSize: 17,
      inputPlaceholder: "#93a1a1",
      inputSendBg: "transparent",
      inputTextColor: "#657b83",
      modeAutoColor: "#b58900",
      modeEditColor: "#268bd2",
      modeVariant: "minimal",
      modelVariant: "minimal",
      msgLineHeight: 1.6,
      msgTextColor: "#657b83",
      pillBg: "#eee8d5",
      pillText: "#586e75",
      prismOnColor: "#859900",
      rightBg: "#eee8d5",
      sendVariant: "minimal",
      sidebarBg: "#eee8d5",
      sidebarGroupSize: 11,
      sidebarNameSize: 13,
      sidebarTextColor: "#586e75",
      spinnerColor: "#b58900",
      spinnerFramePreset: "wave",
      spinnerStalledColor: "#dc322f",
      synComment: "#93a1a1",
      synEntity: "#268bd2",
      synFunction: "#268bd2",
      synKeyword: "#859900",
      synLiteral: "#d33682",
      synMarkupHeading: "#268bd2",
      synProperty: "#657b83",
      synRegex: "#d33682",
      synString: "#2aa198",
      synSupport: "#6c71c4",
      synVariable: "#657b83",
      toolConnectorColor: "#93a1a1",
      toolErr: "#dc322f",
      toolOk: "#859900",
      toolRun: "#268bd2",
      transparency: 1,
      userColor: "#268bd2",
      userTagBg: "#eee8d5",
      userTagText: "#268bd2",
    },
  },
  {
    name: 'amber',
    label: 'Amber CRT',
    // W2-15（F3-B）：delta（相对 THEME_DEFAULTS）——应用时 { ...THEME_DEFAULTS, ...delta } 干净全量换装
    theme: {
      accent: "#ffb000",
      attachVariant: "minimal",
      barFillColor: "#ffb000",
      barHeight: 8,
      barTrackColor: "#2b1900",
      bgBlur: 0,
      ccBg: "#120b00",
      ccBgHeight: 96,
      ccHeight: 96,
      ccHidden: ["send","attach"],
      ccScale: {"pct":95,"tokens":95,"model":95,"mode":95},
      ccStyle: "numeric",
      chatBg: "#120b00",
      chatCodeBg: "transparent",
      chatCodeColor: "#ffe0a3",
      chatFontSize: 15,
      chatLineHeight: 1.55,
      chatTextColor: "#ffcc55",
      cliLineColor: "#9b6b00",
      cliLinePadding: 3,
      cliLineWidth: 2,
      cliPromptColor: "#cc8c00",
      cliTextColor: "#ffcc55",
      diffAdded: "#ffc24b",
      diffAddedWord: "#ffe0a3",
      diffRemoved: "#ff6b35",
      diffRemovedWord: "#ff6b35",
      ekgGreen: "#ffc24b",
      ekgRed: "#ff6b35",
      ekgWidth: 140,
      ekgYellow: "#ffb000",
      globalBgColor: "#120b00",
      globalFont: "system",
      globalFontSize: 15,
      titlebarBg: "#120b00",
      titlebarTextColor: "#ffcc55",
      inputBg: "transparent",
      inputFocusBorder: "#ffb000",
      inputFontSize: 17,
      inputPlaceholder: "#7a5200",
      inputSendBg: "transparent",
      inputTextColor: "#ffcc55",
      modeAutoColor: "#ffb000",
      modeEditColor: "#ffcc55",
      modeVariant: "minimal",
      modelVariant: "minimal",
      msgLineHeight: 1.55,
      msgTextColor: "#ffcc55",
      pillBg: "#2b1900",
      pillText: "#cc8c00",
      prismOnColor: "#ffc24b",
      rightBg: "#120b00",
      sendVariant: "minimal",
      sidebarBg: "#120b00",
      sidebarGroupSize: 11,
      sidebarNameSize: 13,
      sidebarTextColor: "#cc8c00",
      spinnerColor: "#ffb000",
      spinnerFramePreset: "orbit",
      spinnerStalledColor: "#ff6b35",
      synComment: "#9b6b00",
      synEntity: "#ffcc55",
      synFunction: "#ffb000",
      synKeyword: "#ffb000",
      synLiteral: "#ffb000",
      synMarkupHeading: "#ffb000",
      synProperty: "#ffcc55",
      synRegex: "#ffb000",
      synString: "#ffe0a3",
      synSupport: "#ffcc55",
      synVariable: "#ffcc55",
      toolConnectorColor: "#5c3900",
      toolErr: "#ff6b35",
      toolIndicator: "■",
      toolIndicatorGlow: 3,
      toolIndicatorGlowColor: "#ffb000",
      toolOk: "#ffc24b",
      toolRun: "#ffb000",
      transparency: 1,
      uiScheme: "dark",
      userColor: "#ffb000",
      userPrefix: ">",
      userTagBg: "#2b1900",
      userTagText: "#ffcc55",
    },
  }
]

/** 从预设里提取指定 zone 的字段子集 */
export function pickZoneFields(
  theme: Partial<ThemeSettings>,
  zone: string,
): Partial<ThemeSettings> {
  const fields = ZONE_FIELDS[zone] ?? []
  return Object.fromEntries(
    fields.filter((f): f is keyof ThemeSettings => f in theme).map(f => [f, theme[f]]),
  ) as Partial<ThemeSettings>
}
